"""
This type stub file was generated by pyright.
"""

from torch import nn

class CTCHead(nn.Module):
    def __init__(self, in_channels, out_channels=..., fc_decay=..., mid_channels=..., return_feats=..., **kwargs) -> None:
        ...
    
    def forward(self, x, labels=...): # -> Tensor | tuple[Any, Any] | Any:
        ...
    


