"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from pptx.opc.package import XmlPart
from pptx.util import lazyproperty
from pptx.chart.data import ChartData
from pptx.enum.chart import XL_CHART_TYPE
from pptx.package import Package

"""Chart part objects, including Chart and Charts."""
if TYPE_CHECKING:
    ...
class ChartPart(XmlPart):
    """A chart part.

    Corresponds to parts having partnames matching ppt/charts/chart[1-9][0-9]*.xml
    """
    partname_template = ...
    @classmethod
    def new(cls, chart_type: XL_CHART_TYPE, chart_data: ChartData, package: Package): # -> Self:
        """Return new |ChartPart| instance added to `package`.

        Returned chart-part contains a chart of `chart_type` depicting `chart_data`.
        """
        ...
    
    @lazyproperty
    def chart(self): # -> Chart:
        """|Chart| object representing the chart in this part."""
        ...
    
    @lazyproperty
    def chart_workbook(self): # -> ChartWorkbook:
        """
        The |ChartWorkbook| object providing access to the external chart
        data in a linked or embedded Excel workbook.
        """
        ...
    


class ChartWorkbook:
    """Provides access to external chart data in a linked or embedded Excel workbook."""
    def __init__(self, chartSpace, chart_part) -> None:
        ...
    
    def update_from_xlsx_blob(self, xlsx_blob): # -> None:
        """
        Replace the Excel spreadsheet in the related |EmbeddedXlsxPart| with
        the Excel binary in *xlsx_blob*, adding a new |EmbeddedXlsxPart| if
        there isn't one.
        """
        ...
    
    @property
    def xlsx_part(self): # -> None:
        """Optional |EmbeddedXlsxPart| object containing data for this chart.

        This related part has its rId at `c:chartSpace/c:externalData/@rId`. This value
        is |None| if there is no `<c:externalData>` element.
        """
        ...
    
    @xlsx_part.setter
    def xlsx_part(self, xlsx_part): # -> None:
        """
        Set the related |EmbeddedXlsxPart| to *xlsx_part*. Assume one does
        not already exist.
        """
        ...
    


