"""
This type stub file was generated by pyright.
"""

from collections import deque
from typing import Any, Sequence, TYPE_CHECKING
from polyfactory.utils.deprecation import deprecated
from random import Random

if TYPE_CHECKING:
    ...
def unwrap_new_type(annotation: Any) -> Any:
    """Return base type if given annotation is a type derived with NewType, otherwise annotation.

    :param annotation: A type annotation, possibly one created using 'types.NewType'

    :returns: The unwrapped annotation.
    """
    ...

@deprecated("v2.21.0")
def unwrap_union(annotation: Any, random: Random) -> Any:
    """Unwraps union types recursively and picks a random type from each union.

    :param annotation: A type annotation, possibly a type union.
    :param random: An instance of random.Random.
    :returns: A type annotation
    """
    ...

def unwrap_optional(annotation: Any) -> Any:
    """Unwraps optional union types - recursively.

    :param annotation: A type annotation, possibly an optional union.

    :returns: A type annotation
    """
    ...

def unwrap_annotation(annotation: Any, random: Random | None = ...) -> Any:
    """Unwraps an annotation.

    :param annotation: A type annotation.
    :param random: An instance of random.Random.

    :returns: The unwrapped annotation.

    """
    ...

def flatten_annotation(annotation: Any) -> list[Any]:
    """Flattens an annotation into an array of possible types. For example:

    * Union[str, int] → [str, int]
    * Optional[str] → [str, None]
    * Union[str, Optional[int]] → [str, int, None]
    * NewType('UserId', int) → [int]

    :param annotation: A type annotation.

    :returns: The flattened annotations.
    """
    ...

def unwrap_args(annotation: Any, random: Random | None = ...) -> tuple[Any, ...]:
    """Unwrap the annotation and return any type args.

    :param annotation: A type annotation
    :param random: An instance of random.Random.

    :returns: A tuple of type args.

    """
    ...

def unwrap_annotated(annotation: Any, random: Random | None = ...) -> tuple[Any, list[Any]]:
    """Unwrap an annotated type and return a tuple of type args and optional metadata.

    :param annotation: An annotated type annotation
    :param random: An instance of random.Random.

    :returns: A tuple of type args.

    """
    ...

def normalize_annotation(annotation: Any, random: Random | None = ...) -> Any:
    """Normalize an annotation.

    :param annotation: A type annotation.

    :returns: A normalized type annotation.

    """
    ...

def get_annotation_metadata(annotation: Any) -> Sequence[Any]:
    """Get the metadata in the annotation.

    :param annotation: A type annotation.

    :returns: The metadata.
    """
    ...

def get_collection_type(annotation: Any) -> type[list | tuple | set | frozenset | dict | deque]:
    """Get the collection type from the annotation.

    :param annotation: A type annotation.

    :returns: The collection type.
    """
    ...

def is_dataclass_instance(obj: Any) -> bool:
    ...

