"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from collections.abc import Callable, Iterable, Iterator
from typing import Any, Generic, TypeVar
from typing_extensions import ParamSpec

class CoverageContainerBase(ABC):
    """Base class for coverage container implementations.

    A coverage container is a wrapper providing values for a particular field. Coverage containers return field values and
    track a "done" state to indicate that all coverage examples have been generated.
    """
    @abstractmethod
    def next_value(self) -> Any:
        """Provide the next value"""
        ...
    
    @abstractmethod
    def is_done(self) -> bool:
        """Indicate if this container has provided every coverage example it has"""
        ...
    


T = TypeVar("T")
class CoverageContainer(CoverageContainerBase, Generic[T]):
    """A coverage container that wraps a collection of values.

    When calling ``next_value()`` a greater number of times than the length of the given collection will cause duplicate
    examples to be returned (wraps around).

    If there are any coverage containers within the given collection, the values from those containers are essentially merged
    into the parent container.
    """
    def __init__(self, instances: Iterable[T]) -> None:
        ...
    
    def next_value(self) -> T:
        ...
    
    def is_done(self) -> bool:
        ...
    
    def __repr__(self) -> str:
        ...
    


P = ParamSpec("P")
class CoverageContainerCallable(CoverageContainerBase, Generic[T]):
    """A coverage container that wraps a callable.

    When calling ``next_value()`` the wrapped callable is called to provide a value.
    """
    def __init__(self, func: Callable[P, T], *args: P.args, **kwargs: P.kwargs) -> None:
        ...
    
    def next_value(self) -> T:
        ...
    
    def is_done(self) -> bool:
        ...
    


def resolve_kwargs_coverage(kwargs: dict[str, Any]) -> Iterator[dict[str, Any]]:
    ...

