"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from collections.abc import Iterable
from io import BytesIO
from pathlib import Path
from typing import Optional, Set, Union
from docling_core.types.doc import BoundingBox, Size
from docling_core.types.doc.page import SegmentedPdfPage, TextCell
from PIL import Image
from docling.backend.abstract_backend import PaginatedDocumentBackend
from docling.datamodel.backend_options import PdfBackendOptions
from docling.datamodel.base_models import InputFormat
from docling.datamodel.document import InputDocument

"""
This type stub file was generated by pyright.
"""
class PdfPageBackend(ABC):
    @abstractmethod
    def get_text_in_rect(self, bbox: BoundingBox) -> str:
        ...
    
    @abstractmethod
    def get_segmented_page(self) -> Optional[SegmentedPdfPage]:
        ...
    
    @abstractmethod
    def get_text_cells(self) -> Iterable[TextCell]:
        ...
    
    @abstractmethod
    def get_bitmap_rects(self, float: int = ...) -> Iterable[BoundingBox]:
        ...
    
    @abstractmethod
    def get_page_image(self, scale: float = ..., cropbox: Optional[BoundingBox] = ...) -> Image.Image:
        ...
    
    @abstractmethod
    def get_size(self) -> Size:
        ...
    
    @abstractmethod
    def is_valid(self) -> bool:
        ...
    
    @abstractmethod
    def unload(self):
        ...
    


class PdfDocumentBackend(PaginatedDocumentBackend):
    def __init__(self, in_doc: InputDocument, path_or_stream: Union[BytesIO, Path], options: PdfBackendOptions = ...) -> None:
        ...
    
    @abstractmethod
    def load_page(self, page_no: int) -> PdfPageBackend:
        ...
    
    @abstractmethod
    def page_count(self) -> int:
        ...
    
    @classmethod
    def supported_formats(cls) -> Set[InputFormat]:
        ...
    
    @classmethod
    def supports_pagination(cls) -> bool:
        ...
    


