"""
This type stub file was generated by pyright.
"""

from typing import Callable, Iterator, TYPE_CHECKING
from pptx.enum.shapes import MSO_CONNECTOR_TYPE, PP_PLACEHOLDER
from pptx.oxml.shapes.autoshape import CT_Shape
from pptx.oxml.shapes.connector import CT_Connector
from pptx.oxml.shapes.graphfrm import CT_GraphicalObjectFrame
from pptx.oxml.shapes.picture import CT_Picture
from pptx.oxml.shapes.shared import BaseShapeElement, CT_Transform2D
from pptx.oxml.xmlchemy import BaseOxmlElement
from pptx.oxml.shapes import ShapeElement

"""lxml custom element classes for shape-tree-related XML elements."""
if TYPE_CHECKING:
    ...
class CT_GroupShape(BaseShapeElement):
    """Used for shape tree (`p:spTree`) as well as the group shape (`p:grpSp`) elements."""
    nvGrpSpPr: CT_GroupShapeNonVisual = ...
    grpSpPr: CT_GroupShapeProperties = ...
    _shape_tags = ...
    def add_autoshape(self, id_: int, name: str, prst: str, x: int, y: int, cx: int, cy: int) -> CT_Shape:
        """Return new `p:sp` appended to the group/shapetree with specified attributes."""
        ...
    
    def add_cxnSp(self, id_: int, name: str, type_member: MSO_CONNECTOR_TYPE, x: int, y: int, cx: int, cy: int, flipH: bool, flipV: bool) -> CT_Connector:
        """Return new `p:cxnSp` appended to the group/shapetree with the specified attribues."""
        ...
    
    def add_freeform_sp(self, x: int, y: int, cx: int, cy: int) -> CT_Shape:
        """Append a new freeform `p:sp` with specified position and size."""
        ...
    
    def add_grpSp(self) -> CT_GroupShape:
        """Return `p:grpSp` element newly appended to this shape tree.

        The element contains no sub-shapes, is positioned at (0, 0), and has
        width and height of zero.
        """
        ...
    
    def add_pic(self, id_: int, name: str, desc: str, rId: str, x: int, y: int, cx: int, cy: int) -> CT_Picture:
        """Append a `p:pic` shape to the group/shapetree having properties as specified in call."""
        ...
    
    def add_placeholder(self, id_: int, name: str, ph_type: PP_PLACEHOLDER, orient: str, sz: str, idx: int) -> CT_Shape:
        """Append a newly-created placeholder `p:sp` shape having the specified properties."""
        ...
    
    def add_table(self, id_: int, name: str, rows: int, cols: int, x: int, y: int, cx: int, cy: int) -> CT_GraphicalObjectFrame:
        """Append a `p:graphicFrame` shape containing a table as specified in call."""
        ...
    
    def add_textbox(self, id_: int, name: str, x: int, y: int, cx: int, cy: int) -> CT_Shape:
        """Append a newly-created textbox `p:sp` shape having the specified position and size."""
        ...
    
    @property
    def chExt(self):
        """Descendent `p:grpSpPr/a:xfrm/a:chExt` element."""
        ...
    
    @property
    def chOff(self):
        """Descendent `p:grpSpPr/a:xfrm/a:chOff` element."""
        ...
    
    def get_or_add_xfrm(self) -> CT_Transform2D:
        """Return the `a:xfrm` grandchild element, newly-added if not present."""
        ...
    
    def iter_ph_elms(self): # -> Generator[ShapeElement, Any, None]:
        """Generate each placeholder shape child element in document order."""
        ...
    
    def iter_shape_elms(self) -> Iterator[ShapeElement]:
        """Generate each child of this `p:spTree` element that corresponds to a shape.

        Items appear in XML document order.
        """
        ...
    
    @property
    def max_shape_id(self) -> int:
        """Maximum int value assigned as @id in this slide.

        This is generally a shape-id, but ids can be assigned to other
        objects so we just check all @id values anywhere in the document
        (XML id-values have document scope).

        In practice, its minimum value is 1 because the spTree element itself
        is always assigned id="1".
        """
        ...
    
    @classmethod
    def new_grpSp(cls, id_: int, name: str) -> CT_GroupShape:
        """Return new "loose" `p:grpSp` element having `id_` and `name`."""
        ...
    
    def recalculate_extents(self) -> None:
        """Adjust x, y, cx, and cy to incorporate all contained shapes.

        This would typically be called when a contained shape is added,
        removed, or its position or size updated.

        This method is recursive "upwards" since a change in a group shape
        can change the position and size of its containing group.
        """
        ...
    
    @property
    def xfrm(self) -> CT_Transform2D | None:
        """The `a:xfrm` grandchild element or |None| if not found."""
        ...
    


class CT_GroupShapeNonVisual(BaseShapeElement):
    """`p:nvGrpSpPr` element."""
    cNvPr = ...


class CT_GroupShapeProperties(BaseOxmlElement):
    """p:grpSpPr element"""
    get_or_add_xfrm: Callable[[], CT_Transform2D]
    _tag_seq = ...
    xfrm: CT_Transform2D | None = ...
    effectLst = ...


