"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from pptx.oxml.shapes.shared import BaseShapeElement, CT_ShapeProperties
from pptx.oxml.xmlchemy import BaseOxmlElement
from pptx.util import Length

"""lxml custom element classes for picture-related XML elements."""
if TYPE_CHECKING:
    ...
class CT_Picture(BaseShapeElement):
    """`p:pic` element.

    Represents a picture shape (an image placement on a slide).
    """
    nvPicPr = ...
    blipFill = ...
    spPr: CT_ShapeProperties = ...
    @property
    def blip_rId(self) -> str | None:
        """Value of `p:blipFill/a:blip/@r:embed`.

        Returns |None| if not present.
        """
        ...
    
    def crop_to_fit(self, image_size, view_size): # -> None:
        """
        Set cropping values in `p:blipFill/a:srcRect` such that an image of
        *image_size* will stretch to exactly fit *view_size* when its aspect
        ratio is preserved.
        """
        ...
    
    def get_or_add_ln(self):
        """
        Return the <a:ln> grandchild element, newly added if not present.
        """
        ...
    
    @property
    def ln(self):
        """
        ``<a:ln>`` grand-child element or |None| if not present
        """
        ...
    
    @classmethod
    def new_ph_pic(cls, id_, name, desc, rId):
        """
        Return a new `p:pic` placeholder element populated with the supplied
        parameters.
        """
        ...
    
    @classmethod
    def new_pic(cls, shape_id, name, desc, rId, x, y, cx, cy):
        """Return new `<p:pic>` element tree configured with supplied parameters."""
        ...
    
    @classmethod
    def new_video_pic(cls, shape_id: int, shape_name: str, video_rId: str, media_rId: str, poster_frame_rId: str, x: Length, y: Length, cx: Length, cy: Length) -> CT_Picture:
        """Return a new `p:pic` populated with the specified video."""
        ...
    
    @property
    def srcRect_b(self): # -> float | Any:
        """Value of `p:blipFill/a:srcRect/@b` or 0.0 if not present."""
        ...
    
    @srcRect_b.setter
    def srcRect_b(self, value): # -> None:
        ...
    
    @property
    def srcRect_l(self): # -> float | Any:
        """Value of `p:blipFill/a:srcRect/@l` or 0.0 if not present."""
        ...
    
    @srcRect_l.setter
    def srcRect_l(self, value): # -> None:
        ...
    
    @property
    def srcRect_r(self): # -> float | Any:
        """Value of `p:blipFill/a:srcRect/@r` or 0.0 if not present."""
        ...
    
    @srcRect_r.setter
    def srcRect_r(self, value): # -> None:
        ...
    
    @property
    def srcRect_t(self): # -> float | Any:
        """Value of `p:blipFill/a:srcRect/@t` or 0.0 if not present."""
        ...
    
    @srcRect_t.setter
    def srcRect_t(self, value): # -> None:
        ...
    


class CT_PictureNonVisual(BaseOxmlElement):
    """
    ``<p:nvPicPr>`` element, containing non-visual properties for a picture
    shape.
    """
    cNvPr = ...
    nvPr = ...


