"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

"""Check presence of installed packages at runtime."""
_PY_VERSION: str = ...
_package_versions = ...
_CANDIDATES = ...
def is_package_available(package_name: str) -> bool:
    ...

def get_python_version() -> str:
    ...

def get_hf_hub_version() -> str:
    ...

def is_aiohttp_available() -> bool:
    ...

def get_aiohttp_version() -> str:
    ...

def is_fastai_available() -> bool:
    ...

def get_fastai_version() -> str:
    ...

def is_fastapi_available() -> bool:
    ...

def get_fastapi_version() -> str:
    ...

def is_fastcore_available() -> bool:
    ...

def get_fastcore_version() -> str:
    ...

def is_gradio_available() -> bool:
    ...

def get_gradio_version() -> str:
    ...

def is_graphviz_available() -> bool:
    ...

def get_graphviz_version() -> str:
    ...

def is_hf_transfer_available() -> bool:
    ...

def get_hf_transfer_version() -> str:
    ...

def is_xet_available() -> bool:
    ...

def get_xet_version() -> str:
    ...

def is_keras_available() -> bool:
    ...

def get_keras_version() -> str:
    ...

def is_numpy_available() -> bool:
    ...

def get_numpy_version() -> str:
    ...

def is_jinja_available() -> bool:
    ...

def get_jinja_version() -> str:
    ...

def is_pillow_available() -> bool:
    ...

def get_pillow_version() -> str:
    ...

def is_pydantic_available() -> bool:
    ...

def get_pydantic_version() -> str:
    ...

def is_pydot_available() -> bool:
    ...

def get_pydot_version() -> str:
    ...

def is_tensorboard_available() -> bool:
    ...

def get_tensorboard_version() -> str:
    ...

def is_tf_available() -> bool:
    ...

def get_tf_version() -> str:
    ...

def is_torch_available() -> bool:
    ...

def get_torch_version() -> str:
    ...

def is_safetensors_available() -> bool:
    ...

_is_google_colab = ...
def is_notebook() -> bool:
    """Return `True` if code is executed in a notebook (Jupyter, Colab, QTconsole).

    Taken from https://stackoverflow.com/a/39662359.
    Adapted to make it work with Google colab as well.
    """
    ...

def is_google_colab() -> bool:
    """Return `True` if code is executed in a Google colab.

    Taken from https://stackoverflow.com/a/63519730.
    """
    ...

def is_colab_enterprise() -> bool:
    """Return `True` if code is executed in a Google Colab Enterprise environment."""
    ...

def dump_environment_info() -> Dict[str, Any]:
    """Dump information about the machine to help debugging issues.

    Similar helper exist in:
    - `datasets` (https://github.com/huggingface/datasets/blob/main/src/datasets/commands/env.py)
    - `diffusers` (https://github.com/huggingface/diffusers/blob/main/src/diffusers/commands/env.py)
    - `transformers` (https://github.com/huggingface/transformers/blob/main/src/transformers/commands/env.py)
    """
    ...

