"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Union

def generate_device_map(model, num_processes: int = ..., no_split_module_classes=..., max_memory: Optional[dict] = ...): # -> dict[str, int | str | device] | OrderedDict[Any, Any]:
    """
    Calculates the device map for `model` with an offset for PiPPy
    """
    ...

def find_pippy_batch_size(args, kwargs): # -> int | None:
    ...

def build_pipeline(model, split_points, args, kwargs, num_chunks): # -> ScheduleGPipe:
    """
    Attaches the split points to the model based on `self.device_map` and generates a `PipelineStage`. Requires passing
    in needed `args` and `kwargs` as the model needs on the CPU.

    Users can pass in custom `num_chunks` as an optional hyper-parameter. By default will use
    `AcceleratorState.num_processes`
    """
    ...

def pippy_forward(forward, num_chunks, gather_output, *args, **kwargs): # -> Tensor | None:
    ...

def prepare_pippy(model, split_points: Optional[Union[str, list[str]]] = ..., no_split_module_classes: Optional[list[str]] = ..., example_args: Optional[tuple[Any]] = ..., example_kwargs: Optional[dict[str, Any]] = ..., num_chunks: Optional[int] = ..., gather_output: Optional[bool] = ...):
    """
    Wraps `model` for pipeline parallel inference.

    Args:
        model (`torch.nn.Module`):
            A model we want to split for pipeline-parallel inference
        split_points (`str` or `List[str]`, defaults to 'auto'):
            How to generate the split points and chunk the model across each GPU. 'auto' will find the best balanced
            split given any model. Should be a list of layer names in the model to split by otherwise.
        no_split_module_classes (`List[str]`):
            A list of class names for layers we don't want to be split.
        example_args (tuple of model inputs):
            The expected inputs for the model that uses order-based inputs for a *single process*. Recommended to use
            this method if possible.
        example_kwargs (dict of model inputs)
            The expected inputs for the model that uses dictionary-based inputs for a *single process*. This is a
            *highly* limiting structure that requires the same keys be present at *all* inference calls. Not
            recommended unless the prior condition is true for all cases.
        num_chunks (`int`, defaults to the number of available GPUs):
            The number of different stages the Pipeline will have. By default it will assign one chunk per GPU, but
            this can be tuned and played with. In general one should have num_chunks >= num_gpus.
        gather_output (`bool`, defaults to `False`):
            If `True`, the output from the last GPU (which holds the true outputs) is sent across to all GPUs.
    """
    ...

