"""
This type stub file was generated by pyright.
"""

__all__ = ("PdfUnspHandler", )
lib_logger = ...
class PdfUnspHandler:
    """
    Unsupported feature handler helper class.
    
    Attributes:
        handlers (dict[str, typing.Callable]):
            A dictionary of named handler functions to be called with an unsupported code (:attr:`FPDF_UNSP_*`) when PDFium detects an unsupported feature.
    """
    def __init__(self) -> None:
        ...
    
    def __call__(self, _, type): # -> None:
        ...
    
    def setup(self, add_default=...): # -> None:
        """
        Attach the handler to PDFium, and register an exit function to keep the object alive for the rest of the session.
        
        Parameters:
            add_default (bool):
                If True, add a default callback that will log unsupported features as warning.
        """
        ...
    


