"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING, Union
from pydantic_core import CoreSchema, core_schema
from typing_extensions import TypeGuard
from rich.console import Console

if TYPE_CHECKING:
    ...
AnyFunctionSchema = Union[core_schema.AfterValidatorFunctionSchema, core_schema.BeforeValidatorFunctionSchema, core_schema.WrapValidatorFunctionSchema, core_schema.PlainValidatorFunctionSchema,]
FunctionSchemaWithInnerSchema = Union[core_schema.AfterValidatorFunctionSchema, core_schema.BeforeValidatorFunctionSchema, core_schema.WrapValidatorFunctionSchema,]
CoreSchemaField = Union[core_schema.ModelField, core_schema.DataclassField, core_schema.TypedDictField, core_schema.ComputedField]
CoreSchemaOrField = Union[core_schema.CoreSchema, CoreSchemaField]
_CORE_SCHEMA_FIELD_TYPES = ...
_FUNCTION_WITH_INNER_SCHEMA_TYPES = ...
_LIST_LIKE_SCHEMA_WITH_ITEMS_TYPES = ...
def is_core_schema(schema: CoreSchemaOrField) -> TypeGuard[CoreSchema]:
    ...

def is_core_schema_field(schema: CoreSchemaOrField) -> TypeGuard[CoreSchemaField]:
    ...

def is_function_with_inner_schema(schema: CoreSchemaOrField) -> TypeGuard[FunctionSchemaWithInnerSchema]:
    ...

def is_list_like_schema_with_items_schema(schema: CoreSchema) -> TypeGuard[core_schema.ListSchema | core_schema.SetSchema | core_schema.FrozenSetSchema]:
    ...

def get_type_ref(type_: Any, args_override: tuple[type[Any], ...] | None = ...) -> str:
    """Produces the ref to be used for this type by pydantic_core's core schemas.

    This `args_override` argument was added for the purpose of creating valid recursive references
    when creating generic models without needing to create a concrete class.
    """
    ...

def get_ref(s: core_schema.CoreSchema) -> None | str:
    """Get the ref from the schema if it has one.
    This exists just for type checking to work correctly.
    """
    ...

def pretty_print_core_schema(val: Any, *, console: Console | None = ..., max_depth: int | None = ..., strip_metadata: bool = ...) -> None:
    """Pretty-print a core schema using the `rich` library.

    Args:
        val: The core schema to print, or a Pydantic model/dataclass/type adapter
            (in which case the cached core schema is fetched and printed).
        console: A rich console to use when printing. Defaults to the global rich console instance.
        max_depth: The number of nesting levels which may be printed.
        strip_metadata: Whether to strip metadata in the output. If `True` any known core metadata
            attributes will be stripped (but custom attributes are kept). Defaults to `True`.
    """
    ...

pps = ...
