"""
This type stub file was generated by pyright.
"""

from pathlib import Path

"""Git utilities, adopted from mypy's git utilities (https://github.com/python/mypy/blob/master/mypy/git.py)."""
def is_git_repo(dir: Path) -> bool:
    """Is the given directory version-controlled with git?"""
    ...

def have_git() -> bool:
    """Can we run the git executable?"""
    ...

def git_revision(dir: Path) -> str:
    """Get the SHA-1 of the HEAD of a git repository."""
    ...

