"""
This type stub file was generated by pyright.
"""

import datetime as dt
from typing import Callable
from lxml.etree import _Element
from pptx.oxml.xmlchemy import BaseOxmlElement

"""lxml custom element classes for core properties-related XML elements."""
class CT_CoreProperties(BaseOxmlElement):
    """`cp:coreProperties` element.

    The root element of the Core Properties part stored as `/docProps/core.xml`. Implements many
    of the Dublin Core document metadata elements. String elements resolve to an empty string ('')
    if the element is not present in the XML. String elements are limited in length to 255 unicode
    characters.
    """
    get_or_add_revision: Callable[[], _Element]
    category = ...
    contentStatus = ...
    created = ...
    creator = ...
    description = ...
    identifier = ...
    keywords = ...
    language = ...
    lastModifiedBy = ...
    lastPrinted = ...
    modified = ...
    revision: _Element | None = ...
    subject = ...
    title = ...
    version = ...
    _coreProperties_tmpl = ...
    @staticmethod
    def new_coreProperties() -> CT_CoreProperties:
        """Return a new `cp:coreProperties` element"""
        ...
    
    @property
    def author_text(self) -> str:
        ...
    
    @author_text.setter
    def author_text(self, value: str): # -> None:
        ...
    
    @property
    def category_text(self) -> str:
        ...
    
    @category_text.setter
    def category_text(self, value: str): # -> None:
        ...
    
    @property
    def comments_text(self) -> str:
        ...
    
    @comments_text.setter
    def comments_text(self, value: str): # -> None:
        ...
    
    @property
    def contentStatus_text(self) -> str:
        ...
    
    @contentStatus_text.setter
    def contentStatus_text(self, value: str): # -> None:
        ...
    
    @property
    def created_datetime(self): # -> datetime | None:
        ...
    
    @created_datetime.setter
    def created_datetime(self, value: dt.datetime): # -> None:
        ...
    
    @property
    def identifier_text(self) -> str:
        ...
    
    @identifier_text.setter
    def identifier_text(self, value: str): # -> None:
        ...
    
    @property
    def keywords_text(self) -> str:
        ...
    
    @keywords_text.setter
    def keywords_text(self, value: str): # -> None:
        ...
    
    @property
    def language_text(self) -> str:
        ...
    
    @language_text.setter
    def language_text(self, value: str): # -> None:
        ...
    
    @property
    def lastModifiedBy_text(self) -> str:
        ...
    
    @lastModifiedBy_text.setter
    def lastModifiedBy_text(self, value: str): # -> None:
        ...
    
    @property
    def lastPrinted_datetime(self): # -> datetime | None:
        ...
    
    @lastPrinted_datetime.setter
    def lastPrinted_datetime(self, value: dt.datetime): # -> None:
        ...
    
    @property
    def modified_datetime(self): # -> datetime | None:
        ...
    
    @modified_datetime.setter
    def modified_datetime(self, value: dt.datetime): # -> None:
        ...
    
    @property
    def revision_number(self) -> int:
        """Integer value of revision property."""
        ...
    
    @revision_number.setter
    def revision_number(self, value: int): # -> None:
        """Set revision property to string value of integer `value`."""
        ...
    
    @property
    def subject_text(self) -> str:
        ...
    
    @subject_text.setter
    def subject_text(self, value: str): # -> None:
        ...
    
    @property
    def title_text(self) -> str:
        ...
    
    @title_text.setter
    def title_text(self, value: str): # -> None:
        ...
    
    @property
    def version_text(self) -> str:
        ...
    
    @version_text.setter
    def version_text(self, value: str): # -> None:
        ...
    
    _offset_pattern = ...


