"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, Protocol, Sequence, Type
from lxml import etree
from lxml.etree import ElementBase, _Element

"""Base and meta classes enabling declarative definition of custom element classes."""
class AttributeType(Protocol):
    """Interface for an object that can act as an attribute type.

    An attribute-type specifies how values are transformed to and from the XML "string" value of the
    attribute.
    """
    @classmethod
    def from_xml(cls, xml_value: str) -> Any:
        """Transform an attribute value to a Python value."""
        ...
    
    @classmethod
    def to_xml(cls, value: Any) -> str:
        """Transform a Python value to a str value suitable to this XML attribute."""
        ...
    


def OxmlElement(nsptag_str: str, nsmap: dict[str, str] | None = ...) -> BaseOxmlElement:
    """Return a "loose" lxml element having the tag specified by `nsptag_str`.

    `nsptag_str` must contain the standard namespace prefix, e.g. 'a:tbl'. The resulting element is
    an instance of the custom element class for this tag name if one is defined.
    """
    ...

def serialize_for_reading(element: ElementBase): # -> XmlString:
    """
    Serialize *element* to human-readable XML suitable for tests. No XML
    declaration.
    """
    ...

class XmlString(str):
    """Provides string comparison override suitable for serialized XML; useful for tests."""
    _xml_elm_line_patt = ...
    def __eq__(self, other: object) -> bool:
        ...
    
    def __ne__(self, other: object) -> bool:
        ...
    


class MetaOxmlElement(type):
    """Metaclass for BaseOxmlElement."""
    def __init__(cls, clsname: str, bases: tuple[type, ...], clsdict: dict[str, Any]) -> None:
        ...
    


class BaseAttribute:
    """Base class for OptionalAttribute and RequiredAttribute, providing common methods."""
    def __init__(self, attr_name: str, simple_type: type[AttributeType]) -> None:
        ...
    
    def populate_class_members(self, element_cls: Type[BaseOxmlElement], prop_name: str): # -> None:
        """
        Add the appropriate methods to *element_cls*.
        """
        ...
    


class OptionalAttribute(BaseAttribute):
    """Defines an optional attribute on a custom element class.

    An optional attribute returns a default value when not present for reading. When assigned
    |None|, the attribute is removed.
    """
    def __init__(self, attr_name: str, simple_type: type[AttributeType], default: Any = ...) -> None:
        ...
    


class RequiredAttribute(BaseAttribute):
    """Defines a required attribute on a custom element class.

    A required attribute is assumed to be present for reading, so does not have a default value;
    its actual value is always used. If missing on read, an |InvalidXmlError| is raised. It also
    does not remove the attribute if |None| is assigned. Assigning |None| raises |TypeError| or
    |ValueError|, depending on the simple type of the attribute.
    """
    ...


class _BaseChildElement:
    """Base class for the child element classes corresponding to varying cardinalities.

    Subclasses include ZeroOrOne and ZeroOrMore.
    """
    def __init__(self, nsptagname: str, successors: Sequence[str] = ...) -> None:
        ...
    
    def populate_class_members(self, element_cls: Type[BaseOxmlElement], prop_name: str): # -> None:
        """Baseline behavior for adding the appropriate methods to `element_cls`."""
        ...
    


class Choice(_BaseChildElement):
    """Defines a child element belonging to a group, only one of which may appear as a child."""
    @property
    def nsptagname(self): # -> str:
        ...
    
    def populate_class_members(self, element_cls: Type[BaseOxmlElement], group_prop_name: str, successors: Sequence[str]): # -> None:
        """Add the appropriate methods to `element_cls`."""
        ...
    


class OneAndOnlyOne(_BaseChildElement):
    """Defines a required child element for MetaOxmlElement."""
    def __init__(self, nsptagname: str) -> None:
        ...
    
    def populate_class_members(self, element_cls: Type[BaseOxmlElement], prop_name: str): # -> None:
        """
        Add the appropriate methods to *element_cls*.
        """
        ...
    


class OneOrMore(_BaseChildElement):
    """Defines a repeating child element for MetaOxmlElement that must appear at least once."""
    def populate_class_members(self, element_cls: Type[BaseOxmlElement], prop_name: str): # -> None:
        """Add the appropriate methods to *element_cls*."""
        ...
    


class ZeroOrMore(_BaseChildElement):
    """
    Defines an optional repeating child element for MetaOxmlElement.
    """
    def populate_class_members(self, element_cls: Type[BaseOxmlElement], prop_name: str): # -> None:
        """
        Add the appropriate methods to *element_cls*.
        """
        ...
    


class ZeroOrOne(_BaseChildElement):
    """Defines an optional child element for MetaOxmlElement."""
    def populate_class_members(self, element_cls: Type[BaseOxmlElement], prop_name: str): # -> None:
        """Add the appropriate methods to `element_cls`."""
        ...
    


class ZeroOrOneChoice(_BaseChildElement):
    """An `EG_*` element group where at most one of its members may appear as a child."""
    def __init__(self, choices: Iterable[Choice], successors: Iterable[str] = ...) -> None:
        ...
    
    def populate_class_members(self, element_cls: Type[BaseOxmlElement], prop_name: str): # -> None:
        """Add the appropriate methods to `element_cls`."""
        ...
    


class BaseOxmlElement(etree.ElementBase, metaclass=MetaOxmlElement):
    """Effective base class for all custom element classes.

    Adds standardized behavior to all classes in one place.
    """
    def __repr__(self): # -> str:
        ...
    
    def first_child_found_in(self, *tagnames: str) -> _Element | None:
        """First child with tag in `tagnames`, or None if not found."""
        ...
    
    def insert_element_before(self, elm: ElementBase, *tagnames: str):
        ...
    
    def remove_all(self, *tagnames: str) -> None:
        """Remove child elements with tagname (e.g. "a:p") in `tagnames`."""
        ...
    
    @property
    def xml(self) -> str:
        """XML string for this element, suitable for testing purposes.

        Pretty printed for readability and without an XML declaration at the top.
        """
        ...
    
    def xpath(self, xpath_str: str) -> Any:
        """Override of `lxml` _Element.xpath() method.

        Provides standard Open XML namespace mapping (`nsmap`) in centralized location.
        """
        ...
    


