"""
This type stub file was generated by pyright.
"""

import numpy as np
from pathlib import Path
from typing import Any, Union
from PIL import Image

root_dir = ...
InputType = Union[str, np.ndarray, bytes, Path, Image.Image]
class LoadImage:
    def __init__(self) -> None:
        ...
    
    def __call__(self, img: InputType) -> np.ndarray:
        ...
    
    def load_img(self, img: InputType) -> np.ndarray:
        ...
    
    @staticmethod
    def verify_exist(file_path: Union[str, Path]): # -> None:
        ...
    
    @staticmethod
    def exif_transpose(img: Image.Image) -> Image.Image:
        ...
    
    def img_to_ndarray(self, img: Image.Image) -> np.ndarray:
        ...
    
    def convert_img(self, img: np.ndarray, origin_img_type: Any) -> np.ndarray:
        ...
    
    @staticmethod
    def cvt_two_to_three(img: np.ndarray) -> np.ndarray:
        """gray + alpha → BGR"""
        ...
    
    @staticmethod
    def cvt_four_to_three(img: np.ndarray) -> np.ndarray:
        """RGBA → BGR"""
        ...
    


class LoadImageError(Exception):
    ...


