"""
This type stub file was generated by pyright.
"""

import numpy as np
from pathlib import Path
from typing import Tuple, Union

def mkdir(dir_path): # -> None:
    ...

def quads_to_rect_bbox(bbox: np.ndarray) -> Tuple[float, float, float, float]:
    ...

def has_chinese_char(text: str) -> bool:
    ...

def get_file_sha256(file_path: Union[str, Path], chunk_size: int = ...) -> str:
    ...

def save_img(save_path: Union[str, Path], img: np.ndarray): # -> None:
    ...

def is_url(url: str) -> bool:
    ...

def import_package(name, package=...): # -> ModuleType | None:
    ...

