"""
This type stub file was generated by pyright.
"""

import sys

def setup_logging(): # -> None:
    ...

def parse_numtext(numtext): # -> list[Any] | None:
    ...

def round_list(lst, n_digits): # -> tuple[Any, ...] | list[Any]:
    ...

def add_input(parser, pages=...): # -> None:
    ...

def add_n_digits(parser): # -> None:
    ...

def get_input(args, init_forms=..., **kwargs): # -> PdfDocument:
    ...

if sys.version_info >= (3, 9):
    ...
else:
    ...
