"""
This type stub file was generated by pyright.
"""

from dask.callbacks import Callback

__author__ = ...
__all__ = ['TqdmCallback']
class TqdmCallback(Callback):
    """Dask callback for task progress."""
    def __init__(self, start=..., pretask=..., tqdm_class=..., **tqdm_kwargs) -> None:
        """
        Parameters
        ----------
        tqdm_class  : optional
            `tqdm` class to use for bars [default: `tqdm.auto.tqdm`].
        tqdm_kwargs  : optional
            Any other arguments used for all bars.
        """
        ...
    
    def display(self): # -> None:
        """Displays in the current cell in Notebooks."""
        ...
    


