"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from .base import BaseInferenceType, dataclass_with_extra

@dataclass_with_extra
class ImageToImageTargetSize(BaseInferenceType):
    """The size in pixels of the output image. This parameter is only supported by some
    providers and for specific models. It will be ignored when unsupported.
    """
    height: int
    width: int
    ...


@dataclass_with_extra
class ImageToImageParameters(BaseInferenceType):
    """Additional inference parameters for Image To Image"""
    guidance_scale: Optional[float] = ...
    negative_prompt: Optional[str] = ...
    num_inference_steps: Optional[int] = ...
    prompt: Optional[str] = ...
    target_size: Optional[ImageToImageTargetSize] = ...


@dataclass_with_extra
class ImageToImageInput(BaseInferenceType):
    """Inputs for Image To Image inference"""
    inputs: str
    parameters: Optional[ImageToImageParameters] = ...


@dataclass_with_extra
class ImageToImageOutput(BaseInferenceType):
    """Outputs of inference for the Image To Image task"""
    image: Any
    ...


