"""
This type stub file was generated by pyright.
"""

from typing import Optional
from .base import BaseInferenceType, dataclass_with_extra

@dataclass_with_extra
class QuestionAnsweringInputData(BaseInferenceType):
    """One (context, question) pair to answer"""
    context: str
    question: str
    ...


@dataclass_with_extra
class QuestionAnsweringParameters(BaseInferenceType):
    """Additional inference parameters for Question Answering"""
    align_to_words: Optional[bool] = ...
    doc_stride: Optional[int] = ...
    handle_impossible_answer: Optional[bool] = ...
    max_answer_len: Optional[int] = ...
    max_question_len: Optional[int] = ...
    max_seq_len: Optional[int] = ...
    top_k: Optional[int] = ...


@dataclass_with_extra
class QuestionAnsweringInput(BaseInferenceType):
    """Inputs for Question Answering inference"""
    inputs: QuestionAnsweringInputData
    parameters: Optional[QuestionAnsweringParameters] = ...


@dataclass_with_extra
class QuestionAnsweringOutputElement(BaseInferenceType):
    """Outputs of inference for the Question Answering task"""
    answer: str
    end: int
    score: float
    start: int
    ...


