"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Literal, Optional
from .base import BaseInferenceType, dataclass_with_extra

@dataclass_with_extra
class TableQuestionAnsweringInputData(BaseInferenceType):
    """One (table, question) pair to answer"""
    question: str
    table: Dict[str, List[str]]
    ...


Padding = Literal["do_not_pad", "longest", "max_length"]
@dataclass_with_extra
class TableQuestionAnsweringParameters(BaseInferenceType):
    """Additional inference parameters for Table Question Answering"""
    padding: Optional[Padding] = ...
    sequential: Optional[bool] = ...
    truncation: Optional[bool] = ...


@dataclass_with_extra
class TableQuestionAnsweringInput(BaseInferenceType):
    """Inputs for Table Question Answering inference"""
    inputs: TableQuestionAnsweringInputData
    parameters: Optional[TableQuestionAnsweringParameters] = ...


@dataclass_with_extra
class TableQuestionAnsweringOutputElement(BaseInferenceType):
    """Outputs of inference for the Table Question Answering task"""
    answer: str
    cells: List[str]
    coordinates: List[List[int]]
    aggregator: Optional[str] = ...


