"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from .base import BaseInferenceType, dataclass_with_extra

@dataclass_with_extra
class VisualQuestionAnsweringInputData(BaseInferenceType):
    """One (image, question) pair to answer"""
    image: Any
    question: str
    ...


@dataclass_with_extra
class VisualQuestionAnsweringParameters(BaseInferenceType):
    """Additional inference parameters for Visual Question Answering"""
    top_k: Optional[int] = ...


@dataclass_with_extra
class VisualQuestionAnsweringInput(BaseInferenceType):
    """Inputs for Visual Question Answering inference"""
    inputs: VisualQuestionAnsweringInputData
    parameters: Optional[VisualQuestionAnsweringParameters] = ...


@dataclass_with_extra
class VisualQuestionAnsweringOutputElement(BaseInferenceType):
    """Outputs of inference for the Visual Question Answering task"""
    score: float
    answer: Optional[str] = ...


