"""
This type stub file was generated by pyright.
"""

from abc import ABC
from typing import Any
from polyfactory.utils.deprecation import deprecated

class CollectionExtender(ABC):
    __types__: tuple[type, ...]
    @classmethod
    @deprecated("2.20.0")
    def extend_type_args(cls, annotation_alias: Any, type_args: tuple[Any, ...], number_of_args: int) -> tuple[Any, ...]:
        ...
    


class TupleExtender(CollectionExtender):
    __types__ = ...


class ListLikeExtender(CollectionExtender):
    __types__ = ...


class SetExtender(CollectionExtender):
    __types__ = ...


class DictExtender(CollectionExtender):
    __types__ = ...


class FallbackExtender(CollectionExtender):
    __types__ = ...


