"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional
from docx.document import Document
from PIL import Image

def get_libreoffice_cmd(raise_if_unavailable: bool = ...) -> Optional[str]:
    """Return the libreoffice cmd and optionally test it."""
    ...

def get_docx_to_pdf_converter() -> Optional[Callable]:
    """
    Detects the best available DOCX to PDF tool and returns a conversion function.
    The returned function accepts (input_path, output_path).
    Returns None if no tool is available.
    """
    ...

def crop_whitespace(image: Image.Image, bg_color=..., padding=...) -> Image.Image:
    ...

def get_pil_from_dml_docx(docx: Document, converter: Optional[Callable]) -> Optional[Image.Image]:
    ...

