"""
This type stub file was generated by pyright.
"""

from pptx.oxml.xmlchemy import BaseOxmlElement

"""lxml custom element classes for DrawingML-related XML elements."""
class _BaseColorElement(BaseOxmlElement):
    """
    Base class for <a:srgbClr> and <a:schemeClr> elements.
    """
    lumMod = ...
    lumOff = ...
    def add_lumMod(self, value):
        """
        Return a newly added <a:lumMod> child element.
        """
        ...
    
    def add_lumOff(self, value):
        """
        Return a newly added <a:lumOff> child element.
        """
        ...
    
    def clear_lum(self): # -> Self:
        """
        Return self after removing any <a:lumMod> and <a:lumOff> child
        elements.
        """
        ...
    


class CT_Color(BaseOxmlElement):
    """Custom element class for `a:fgClr`, `a:bgClr` and perhaps others."""
    eg_colorChoice = ...


class CT_HslColor(_BaseColorElement):
    """
    Custom element class for <a:hslClr> element.
    """
    ...


class CT_Percentage(BaseOxmlElement):
    """
    Custom element class for <a:lumMod> and <a:lumOff> elements.
    """
    val = ...


class CT_PresetColor(_BaseColorElement):
    """
    Custom element class for <a:prstClr> element.
    """
    ...


class CT_SchemeColor(_BaseColorElement):
    """
    Custom element class for <a:schemeClr> element.
    """
    val = ...


class CT_ScRgbColor(_BaseColorElement):
    """
    Custom element class for <a:scrgbClr> element.
    """
    ...


class CT_SRgbColor(_BaseColorElement):
    """
    Custom element class for <a:srgbClr> element.
    """
    val = ...


class CT_SystemColor(_BaseColorElement):
    """
    Custom element class for <a:sysClr> element.
    """
    ...


