"""
This type stub file was generated by pyright.
"""

from pptx.oxml.xmlchemy import BaseOxmlElement

"""lxml custom element classes for DrawingML-related XML elements."""
class CT_Blip(BaseOxmlElement):
    """
    <a:blip> element
    """
    rEmbed = ...


class CT_BlipFillProperties(BaseOxmlElement):
    """
    Custom element class for <a:blipFill> element.
    """
    _tag_seq = ...
    blip = ...
    srcRect = ...
    def crop(self, cropping): # -> None:
        """
        Set `a:srcRect` child to crop according to *cropping* values.
        """
        ...
    


class CT_GradientFillProperties(BaseOxmlElement):
    """`a:gradFill` custom element class."""
    _tag_seq = ...
    gsLst = ...
    lin = ...
    path = ...
    @classmethod
    def new_gradFill(cls):
        """Return newly-created "loose" default gradient subtree."""
        ...
    


class CT_GradientStop(BaseOxmlElement):
    """`a:gs` custom element class."""
    eg_colorChoice = ...
    pos = ...


class CT_GradientStopList(BaseOxmlElement):
    """`a:gsLst` custom element class."""
    gs = ...
    @classmethod
    def new_gsLst(cls):
        """Return newly-created "loose" default stop-list subtree.

        An `a:gsLst` element must have at least two `a:gs` children. These
        are the default from the PowerPoint built-in "White" template.
        """
        ...
    


class CT_GroupFillProperties(BaseOxmlElement):
    """`a:grpFill` custom element class"""
    ...


class CT_LinearShadeProperties(BaseOxmlElement):
    """`a:lin` custom element class"""
    ang = ...


class CT_NoFillProperties(BaseOxmlElement):
    """`a:noFill` custom element class"""
    ...


class CT_PatternFillProperties(BaseOxmlElement):
    """`a:pattFill` custom element class"""
    _tag_seq = ...
    fgClr = ...
    bgClr = ...
    prst = ...


class CT_RelativeRect(BaseOxmlElement):
    """`a:srcRect` element and perhaps others."""
    l = ...
    t = ...
    r = ...
    b = ...


class CT_SolidColorFillProperties(BaseOxmlElement):
    """`a:solidFill` custom element class."""
    eg_colorChoice = ...


