"""
This type stub file was generated by pyright.
"""

from pptx.enum.base import BaseEnum, BaseXmlEnum

"""Enumerations used by text and related objects."""
class MSO_AUTO_SIZE(BaseEnum):
    """Determines the type of automatic sizing allowed.

    The following names can be used to specify the automatic sizing behavior used to fit a shape's
    text within the shape bounding box, for example::

        from pptx.enum.text import MSO_AUTO_SIZE

        shape.text_frame.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE

    The word-wrap setting of the text frame interacts with the auto-size setting to determine the
    specific auto-sizing behavior.

    Note that `TextFrame.auto_size` can also be set to |None|, which removes the auto size setting
    altogether. This causes the setting to be inherited, either from the layout placeholder, in the
    case of a placeholder shape, or from the theme.

    MS API Name: `MsoAutoSize`

    http://msdn.microsoft.com/en-us/library/office/ff865367(v=office.15).aspx
    """
    NONE = ...
    SHAPE_TO_FIT_TEXT = ...
    TEXT_TO_FIT_SHAPE = ...
    MIXED = ...


class MSO_TEXT_UNDERLINE_TYPE(BaseXmlEnum):
    """
    Indicates the type of underline for text. Used with
    :attr:`.Font.underline` to specify the style of text underlining.

    Alias: ``MSO_UNDERLINE``

    Example::

        from pptx.enum.text import MSO_UNDERLINE

        run.font.underline = MSO_UNDERLINE.DOUBLE_LINE

    MS API Name: `MsoTextUnderlineType`

    http://msdn.microsoft.com/en-us/library/aa432699.aspx
    """
    NONE = ...
    DASH_HEAVY_LINE = ...
    DASH_LINE = ...
    DASH_LONG_HEAVY_LINE = ...
    DASH_LONG_LINE = ...
    DOT_DASH_HEAVY_LINE = ...
    DOT_DASH_LINE = ...
    DOT_DOT_DASH_HEAVY_LINE = ...
    DOT_DOT_DASH_LINE = ...
    DOTTED_HEAVY_LINE = ...
    DOTTED_LINE = ...
    DOUBLE_LINE = ...
    HEAVY_LINE = ...
    SINGLE_LINE = ...
    WAVY_DOUBLE_LINE = ...
    WAVY_HEAVY_LINE = ...
    WAVY_LINE = ...
    WORDS = ...
    MIXED = ...


MSO_UNDERLINE = MSO_TEXT_UNDERLINE_TYPE
class MSO_VERTICAL_ANCHOR(BaseXmlEnum):
    """Specifies the vertical alignment of text in a text frame.

    Used with the `.vertical_anchor` property of the |TextFrame| object. Note that the
    `vertical_anchor` property can also have the value None, indicating there is no directly
    specified vertical anchor setting and its effective value is inherited from its placeholder if
    it has one or from the theme. |None| may also be assigned to remove an explicitly specified
    vertical anchor setting.

    MS API Name: `MsoVerticalAnchor`

    http://msdn.microsoft.com/en-us/library/office/ff865255.aspx
    """
    TOP = ...
    MIDDLE = ...
    BOTTOM = ...
    MIXED = ...


MSO_ANCHOR = MSO_VERTICAL_ANCHOR
class PP_PARAGRAPH_ALIGNMENT(BaseXmlEnum):
    """Specifies the horizontal alignment for one or more paragraphs.

    Alias: `PP_ALIGN`

    Example::

        from pptx.enum.text import PP_ALIGN

        shape.paragraphs[0].alignment = PP_ALIGN.CENTER

    MS API Name: `PpParagraphAlignment`

    http://msdn.microsoft.com/en-us/library/office/ff745375(v=office.15).aspx
    """
    CENTER = ...
    DISTRIBUTE = ...
    JUSTIFY = ...
    JUSTIFY_LOW = ...
    LEFT = ...
    RIGHT = ...
    THAI_DISTRIBUTE = ...
    MIXED = ...


PP_ALIGN = PP_PARAGRAPH_ALIGNMENT
