"""
This type stub file was generated by pyright.
"""

from openpyxl.descriptors import Bool, Strict
from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors.nested import NestedText

"""Implementation of custom properties see § 22.3 in the specification"""
class NestedBoolText(Bool, NestedText):
    """
    Descriptor for handling nested elements with the value stored in the text part
    """
    ...


class _CustomDocumentProperty(Serialisable):
    """
    Low-level representation of a Custom Document Property.
    Not used directly
    Must always contain a child element, even if this is empty
    """
    tagname = ...
    _typ = ...
    name = ...
    lpwstr = ...
    i4 = ...
    r8 = ...
    filetime = ...
    bool = ...
    linkTarget = ...
    fmtid = ...
    pid = ...
    def __init__(self, name=..., pid=..., fmtid=..., linkTarget=..., **kw) -> None:
        ...
    
    @property
    def type(self): # -> Literal['linkTarget'] | None:
        ...
    
    def to_tree(self, tagname=..., idx=..., namespace=...): # -> Element[str | Any]:
        ...
    


class _CustomDocumentPropertyList(Serialisable):
    """
    Parses and seriliases property lists but is not used directly
    """
    tagname = ...
    property = ...
    customProps = ...
    def __init__(self, property=...) -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def to_tree(self, tagname=..., idx=..., namespace=...): # -> Element[str | Any]:
        ...
    


class _TypedProperty(Strict):
    name = ...
    def __init__(self, name, value) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class IntProperty(_TypedProperty):
    value = ...


class FloatProperty(_TypedProperty):
    value = ...


class StringProperty(_TypedProperty):
    value = ...


class DateTimeProperty(_TypedProperty):
    value = ...


class BoolProperty(_TypedProperty):
    value = ...


class LinkProperty(_TypedProperty):
    value = ...


CLASS_MAPPING = ...
XML_MAPPING = ...
class CustomPropertyList(Strict):
    props = ...
    def __init__(self) -> None:
        ...
    
    @classmethod
    def from_tree(cls, tree): # -> Self:
        """
        Create list from OOXML element
        """
        ...
    
    def append(self, prop): # -> None:
        ...
    
    def to_tree(self): # -> Element[str | Any]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    @property
    def names(self): # -> list[Any]:
        """List of property names"""
        ...
    
    def __getitem__(self, name):
        """
        Get property by name
        """
        ...
    
    def __delitem__(self, name): # -> None:
        """
        Delete a propery by name
        """
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __iter__(self):
        ...
    


