"""
This type stub file was generated by pyright.
"""

from openpyxl.descriptors.serialisable import Serialisable
from openpyxl.descriptors.container import ElementList

class Relationship(Serialisable):
    """Represents many kinds of relationships."""
    tagname = ...
    Type = ...
    Target = ...
    target = ...
    TargetMode = ...
    Id = ...
    id = ...
    def __init__(self, Id=..., Type=..., type=..., Target=..., TargetMode=...) -> None:
        """
        `type` can be used as a shorthand with the default relationships namespace
        otherwise the `Type` must be a fully qualified URL
        """
        ...
    


class RelationshipList(ElementList):
    tagname = ...
    expected_type = ...
    def append(self, value): # -> None:
        ...
    
    def find(self, content_type): # -> Generator[Any, Any, None]:
        """
        Find relationships by content-type
        NB. these content-types namespaced objects and different to the MIME-types
        in the package manifest :-(
        """
        ...
    
    def get(self, key):
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Return a dictionary of relations keyed by id"""
        ...
    
    def to_tree(self): # -> Element[Any]:
        ...
    


def get_rels_path(path): # -> str:
    """
    Convert relative path to absolutes that can be loaded from a zip
    archive.
    The path to be passed in is that of containing object (workbook,
    worksheet, etc.)
    """
    ...

def get_dependents(archive, filename): # -> RelationshipList:
    """
    Normalise dependency file paths to absolute ones

    Relative paths are relative to parent object
    """
    ...

def get_rel(archive, deps, id=..., cls=...): # -> None:
    """
    Get related object based on id or rel_type
    """
    ...

