"""
This type stub file was generated by pyright.
"""

from typing import Optional
from PIL.Image import Image
from pydantic import BaseModel
from typing_extensions import override
from docling_core.transforms.visualizer.base import BaseVisualizer
from docling_core.types.doc.document import ContentLayer, DoclingDocument

"""Define classes for reading order visualization."""
class _NumberDrawingData(BaseModel):
    xy: tuple[float, float]
    text: str
    ...


class ReadingOrderVisualizer(BaseVisualizer):
    """Reading order visualizer."""
    class Params(BaseModel):
        """Layout visualization parameters."""
        show_label: bool = ...
        show_branch_numbering: bool = ...
        content_layers: set[ContentLayer] = ...
    
    
    base_visualizer: Optional[BaseVisualizer] = ...
    params: Params = ...
    @override
    def get_visualization(self, *, doc: DoclingDocument, **kwargs) -> dict[Optional[int], Image]:
        """Get visualization of the document as images by page."""
        ...
    


