"""
This type stub file was generated by pyright.
"""

"""
Utility list for top level containers that contain one type of element

Provides the necessary API to read and write XML
"""
class ElementList(list):
    @property
    def tagname(self):
        ...
    
    @property
    def expected_type(self):
        ...
    
    @classmethod
    def from_tree(cls, tree): # -> Self:
        ...
    
    def to_tree(self): # -> Element[Any]:
        ...
    
    def append(self, value): # -> None:
        ...
    


