"""
This type stub file was generated by pyright.
"""

from . import Integer, MatchPattern, MinMax, String
from .serialisable import Serialisable

"""
Excel specific descriptors
"""
class HexBinary(MatchPattern):
    pattern = ...


class UniversalMeasure(MatchPattern):
    pattern = ...


class TextPoint(MinMax):
    """
    Size in hundredths of points.
    In theory other units of measurement can be used but these are unbounded
    """
    expected_type = int
    min = ...
    max = ...


Coordinate = Integer
class Percentage(MinMax):
    pattern = ...
    min = ...
    max = ...
    def __set__(self, instance, value): # -> None:
        ...
    


class Extension(Serialisable):
    uri = ...
    def __init__(self, uri=...) -> None:
        ...
    


class ExtensionList(Serialisable):
    ext = ...
    def __init__(self, ext=...) -> None:
        ...
    


class Relation(String):
    namespace = ...
    allow_none = ...


class Base64Binary(MatchPattern):
    pattern = ...


class Guid(MatchPattern):
    pattern = ...


class CellRange(MatchPattern):
    pattern = ...
    allow_none = ...
    def __set__(self, instance, value): # -> None:
        ...
    


