"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from docx.enum.text import WD_COLOR_INDEX, WD_UNDERLINE
from docx.shared import ElementProxy, Length
from docx.oxml.text.run import CT_R

"""Font-related proxy objects."""
if TYPE_CHECKING:
    ...
class Font(ElementProxy):
    """Proxy object for parent of a `<w:rPr>` element and providing access to
    character properties such as font name, font size, bold, and subscript."""
    def __init__(self, r: CT_R, parent: Any | None = ...) -> None:
        ...
    
    @property
    def all_caps(self) -> bool | None:
        """Read/write.

        Causes text in this font to appear in capital letters.
        """
        ...
    
    @all_caps.setter
    def all_caps(self, value: bool | None) -> None:
        ...
    
    @property
    def bold(self) -> bool | None:
        """Read/write.

        Causes text in this font to appear in bold.
        """
        ...
    
    @bold.setter
    def bold(self, value: bool | None) -> None:
        ...
    
    @property
    def color(self): # -> ColorFormat:
        """A |ColorFormat| object providing a way to get and set the text color for this
        font."""
        ...
    
    @property
    def complex_script(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, causes the characters in the run to be treated as complex script
        regardless of their Unicode values.
        """
        ...
    
    @complex_script.setter
    def complex_script(self, value: bool | None) -> None:
        ...
    
    @property
    def cs_bold(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, causes the complex script characters in the run to be displayed in
        bold typeface.
        """
        ...
    
    @cs_bold.setter
    def cs_bold(self, value: bool | None) -> None:
        ...
    
    @property
    def cs_italic(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, causes the complex script characters in the run to be displayed in
        italic typeface.
        """
        ...
    
    @cs_italic.setter
    def cs_italic(self, value: bool | None) -> None:
        ...
    
    @property
    def double_strike(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, causes the text in the run to appear with double strikethrough.
        """
        ...
    
    @double_strike.setter
    def double_strike(self, value: bool | None) -> None:
        ...
    
    @property
    def emboss(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, causes the text in the run to appear as if raised off the page in
        relief.
        """
        ...
    
    @emboss.setter
    def emboss(self, value: bool | None) -> None:
        ...
    
    @property
    def hidden(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, causes the text in the run to be hidden from display, unless
        applications settings force hidden text to be shown.
        """
        ...
    
    @hidden.setter
    def hidden(self, value: bool | None) -> None:
        ...
    
    @property
    def highlight_color(self) -> WD_COLOR_INDEX | None:
        """Color of highlighing applied or |None| if not highlighted."""
        ...
    
    @highlight_color.setter
    def highlight_color(self, value: WD_COLOR_INDEX | None): # -> None:
        ...
    
    @property
    def italic(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, causes the text of the run to appear in italics. |None| indicates
        the effective value is inherited from the style hierarchy.
        """
        ...
    
    @italic.setter
    def italic(self, value: bool | None) -> None:
        ...
    
    @property
    def imprint(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, causes the text in the run to appear as if pressed into the page.
        """
        ...
    
    @imprint.setter
    def imprint(self, value: bool | None) -> None:
        ...
    
    @property
    def math(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, specifies this run contains WML that should be handled as though it
        was Office Open XML Math.
        """
        ...
    
    @math.setter
    def math(self, value: bool | None) -> None:
        ...
    
    @property
    def name(self) -> str | None:
        """The typeface name for this |Font|.

        Causes the text it controls to appear in the named font, if a matching font is
        found. |None| indicates the typeface is inherited from the style hierarchy.
        """
        ...
    
    @name.setter
    def name(self, value: str | None) -> None:
        ...
    
    @property
    def no_proof(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, specifies that the contents of this run should not report any
        errors when the document is scanned for spelling and grammar.
        """
        ...
    
    @no_proof.setter
    def no_proof(self, value: bool | None) -> None:
        ...
    
    @property
    def outline(self) -> bool | None:
        """Read/write tri-state value.

        When |True| causes the characters in the run to appear as if they have an
        outline, by drawing a one pixel wide border around the inside and outside
        borders of each character glyph.
        """
        ...
    
    @outline.setter
    def outline(self, value: bool | None) -> None:
        ...
    
    @property
    def rtl(self) -> bool | None:
        """Read/write tri-state value.

        When |True| causes the text in the run to have right-to-left characteristics.
        """
        ...
    
    @rtl.setter
    def rtl(self, value: bool | None) -> None:
        ...
    
    @property
    def shadow(self) -> bool | None:
        """Read/write tri-state value.

        When |True| causes the text in the run to appear as if each character has a
        shadow.
        """
        ...
    
    @shadow.setter
    def shadow(self, value: bool | None) -> None:
        ...
    
    @property
    def size(self) -> Length | None:
        """Font height in English Metric Units (EMU).

        |None| indicates the font size should be inherited from the style hierarchy.
        |Length| is a subclass of |int| having properties for convenient conversion into
        points or other length units. The :class:`docx.shared.Pt` class allows
        convenient specification of point values::

            >>> font.size = Pt(24)
            >>> font.size
            304800
            >>> font.size.pt
            24.0

        """
        ...
    
    @size.setter
    def size(self, emu: int | Length | None) -> None:
        ...
    
    @property
    def small_caps(self) -> bool | None:
        """Read/write tri-state value.

        When |True| causes the lowercase characters in the run to appear as capital
        letters two points smaller than the font size specified for the run.
        """
        ...
    
    @small_caps.setter
    def small_caps(self, value: bool | None) -> None:
        ...
    
    @property
    def snap_to_grid(self) -> bool | None:
        """Read/write tri-state value.

        When |True| causes the run to use the document grid characters per line settings
        defined in the docGrid element when laying out the characters in this run.
        """
        ...
    
    @snap_to_grid.setter
    def snap_to_grid(self, value: bool | None) -> None:
        ...
    
    @property
    def spec_vanish(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, specifies that the given run shall always behave as if it is
        hidden, even when hidden text is being displayed in the current document. The
        property has a very narrow, specialized use related to the table of contents.
        Consult the spec (§17.3.2.36) for more details.
        """
        ...
    
    @spec_vanish.setter
    def spec_vanish(self, value: bool | None) -> None:
        ...
    
    @property
    def strike(self) -> bool | None:
        """Read/write tri-state value.

        When |True| causes the text in the run to appear with a single horizontal line
        through the center of the line.
        """
        ...
    
    @strike.setter
    def strike(self, value: bool | None) -> None:
        ...
    
    @property
    def subscript(self) -> bool | None:
        """Boolean indicating whether the characters in this |Font| appear as subscript.

        |None| indicates the subscript/subscript value is inherited from the style
        hierarchy.
        """
        ...
    
    @subscript.setter
    def subscript(self, value: bool | None) -> None:
        ...
    
    @property
    def superscript(self) -> bool | None:
        """Boolean indicating whether the characters in this |Font| appear as
        superscript.

        |None| indicates the subscript/superscript value is inherited from the style
        hierarchy.
        """
        ...
    
    @superscript.setter
    def superscript(self, value: bool | None) -> None:
        ...
    
    @property
    def underline(self) -> bool | WD_UNDERLINE | None:
        """The underline style for this |Font|.

        The value is one of |None|, |True|, |False|, or a member of :ref:`WdUnderline`.

        |None| indicates the font inherits its underline value from the style hierarchy.
        |False| indicates no underline. |True| indicates single underline. The values
        from :ref:`WdUnderline` are used to specify other outline styles such as double,
        wavy, and dotted.
        """
        ...
    
    @underline.setter
    def underline(self, value: bool | WD_UNDERLINE | None) -> None:
        ...
    
    @property
    def web_hidden(self) -> bool | None:
        """Read/write tri-state value.

        When |True|, specifies that the contents of this run shall be hidden when the
        document is displayed in web page view.
        """
        ...
    
    @web_hidden.setter
    def web_hidden(self, value: bool | None) -> None:
        ...
    


