"""
This type stub file was generated by pyright.
"""

from torch import nn

class BaseModel(nn.Module):
    def __init__(self, config, **kwargs) -> None:
        """
        the module for OCR.
        args:
            config (dict): the super parameters for module.
        """
        ...
    
    def forward(self, x): # -> dict[Any, Any] | dict[str, Any] | Any:
        ...
    


