"""
This type stub file was generated by pyright.
"""

from typing import Callable
from . import Image

class Iterator:
    """
    This class implements an iterator object that can be used to loop
    over an image sequence.

    You can use the ``[]`` operator to access elements by index. This operator
    will raise an :py:exc:`IndexError` if you try to access a nonexistent
    frame.

    :param im: An image object.
    """
    def __init__(self, im: Image.Image) -> None:
        ...
    
    def __getitem__(self, ix: int) -> Image.Image:
        ...
    
    def __iter__(self) -> Iterator:
        ...
    
    def __next__(self) -> Image.Image:
        ...
    


def all_frames(im: Image.Image | list[Image.Image], func: Callable[[Image.Image], Image.Image] | None = ...) -> list[Image.Image]:
    """
    Applies a given function to all frames in an image or a list of images.
    The frames are returned as a list of separate images.

    :param im: An image, or a list of images.
    :param func: The function to apply to all of the image frames.
    :returns: A list of images.
    """
    ...

