"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable
from . import Image

class _Operand:
    """Wraps an image operand, providing standard operators"""
    def __init__(self, im: Image.Image) -> None:
        ...
    
    def apply(self, op: str, im1: _Operand | float, im2: _Operand | float | None = ..., mode: str | None = ...) -> _Operand:
        ...
    
    def __bool__(self) -> bool:
        ...
    
    def __abs__(self) -> _Operand:
        ...
    
    def __pos__(self) -> _Operand:
        ...
    
    def __neg__(self) -> _Operand:
        ...
    
    def __add__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __radd__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __sub__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __rsub__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __mul__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __rmul__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __truediv__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __rtruediv__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __mod__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __rmod__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __pow__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __rpow__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __invert__(self) -> _Operand:
        ...
    
    def __and__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __rand__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __or__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __ror__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __xor__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __rxor__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __lshift__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __rshift__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __eq__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __ne__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __lt__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __le__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __gt__(self, other: _Operand | float) -> _Operand:
        ...
    
    def __ge__(self, other: _Operand | float) -> _Operand:
        ...
    


def imagemath_int(self: _Operand) -> _Operand:
    ...

def imagemath_float(self: _Operand) -> _Operand:
    ...

def imagemath_equal(self: _Operand, other: _Operand | float | None) -> _Operand:
    ...

def imagemath_notequal(self: _Operand, other: _Operand | float | None) -> _Operand:
    ...

def imagemath_min(self: _Operand, other: _Operand | float | None) -> _Operand:
    ...

def imagemath_max(self: _Operand, other: _Operand | float | None) -> _Operand:
    ...

def imagemath_convert(self: _Operand, mode: str) -> _Operand:
    ...

ops = ...
def lambda_eval(expression: Callable[[dict[str, Any]], Any], options: dict[str, Any] = ..., **kw: Any) -> Any:
    """
    Returns the result of an image function.

    :py:mod:`~PIL.ImageMath` only supports single-layer images. To process multi-band
    images, use the :py:meth:`~PIL.Image.Image.split` method or
    :py:func:`~PIL.Image.merge` function.

    :param expression: A function that receives a dictionary.
    :param options: Values to add to the function's dictionary. Deprecated.
                    You can instead use one or more keyword arguments.
    :param **kw: Values to add to the function's dictionary.
    :return: The expression result. This is usually an image object, but can
             also be an integer, a floating point value, or a pixel tuple,
             depending on the expression.
    """
    ...

def unsafe_eval(expression: str, options: dict[str, Any] = ..., **kw: Any) -> Any:
    """
    Evaluates an image expression. This uses Python's ``eval()`` function to process
    the expression string, and carries the security risks of doing so. It is not
    recommended to process expressions without considering this.
    :py:meth:`~lambda_eval` is a more secure alternative.

    :py:mod:`~PIL.ImageMath` only supports single-layer images. To process multi-band
    images, use the :py:meth:`~PIL.Image.Image.split` method or
    :py:func:`~PIL.Image.merge` function.

    :param expression: A string containing a Python-style expression.
    :param options: Values to add to the evaluation context. Deprecated.
                    You can instead use one or more keyword arguments.
    :param **kw: Values to add to the evaluation context.
    :return: The evaluated expression. This is usually an image object, but can
             also be an integer, a floating point value, or a pixel tuple,
             depending on the expression.
    """
    ...

def eval(expression: str, _dict: dict[str, Any] = ..., **kw: Any) -> Any:
    """
    Evaluates an image expression.

    Deprecated. Use lambda_eval() or unsafe_eval() instead.

    :param expression: A string containing a Python-style expression.
    :param _dict: Values to add to the evaluation context.  You
                  can either use a dictionary, or one or more keyword
                  arguments.
    :return: The evaluated expression. This is usually an image object, but can
             also be an integer, a floating point value, or a pixel tuple,
             depending on the expression.

    ..  deprecated:: 10.3.0
    """
    ...

