"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from . import Image, ImageFile

COMPRESSION = ...
def __getattr__(name: str) -> bytes:
    ...

def i(c: bytes) -> int:
    """.. deprecated:: 10.2.0"""
    ...

def dump(c: Sequence[int | bytes]) -> None:
    """.. deprecated:: 10.2.0"""
    ...

class IptcImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def getint(self, key: tuple[int, int]) -> int:
        ...
    
    def field(self) -> tuple[tuple[int, int] | None, int]:
        ...
    
    def load(self) -> Image.core.PixelAccess | None:
        ...
    


def getiptcinfo(im: ImageFile.ImageFile) -> dict[tuple[int, int], bytes | list[bytes]] | None:
    """
    Get IPTC information from TIFF, JPEG, or IPTC file.

    :param im: An image containing IPTC data.
    :returns: A dictionary containing IPTC information, or None if
        no IPTC information block was found.
    """
    class FakeImage:
        ...
    
    

