"""
This type stub file was generated by pyright.
"""

from . import Image, ImageFile

xpm_head = ...
class XpmImageFile(ImageFile.ImageFile):
    format = ...
    format_description = ...
    def load_read(self, read_bytes: int) -> bytes:
        ...
    


class XpmDecoder(ImageFile.PyDecoder):
    _pulls_fd = ...
    def decode(self, buffer: bytes | Image.SupportsArrayInterface) -> tuple[int, int]:
        ...
    


