"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional, Union
from huggingface_hub.inference._common import RequestParameters
from ._common import BaseConversationalTask, BaseTextGenerationTask

_PROVIDER = ...
_BASE_URL = ...
class FeatherlessTextGenerationTask(BaseTextGenerationTask):
    def __init__(self) -> None:
        ...
    
    def get_response(self, response: Union[bytes, Dict], request_params: Optional[RequestParameters] = ...) -> Any:
        ...
    


class FeatherlessConversationalTask(BaseConversationalTask):
    def __init__(self) -> None:
        ...
    


