"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from pptx.util import lazyproperty

"""Data point-related objects."""
class _BasePoints(Sequence):
    """
    Sequence providing access to the individual data points in a series.
    """
    def __init__(self, ser) -> None:
        ...
    
    def __getitem__(self, idx): # -> Point:
        ...
    


class BubblePoints(_BasePoints):
    """
    Sequence providing access to the individual data points in
    a |BubbleSeries| object.
    """
    def __len__(self):
        ...
    


class CategoryPoints(_BasePoints):
    """
    Sequence providing access to individual |Point| objects, each
    representing the visual properties of a data point in the specified
    category series.
    """
    def __len__(self):
        ...
    


class Point:
    """
    Provides access to the properties of an individual data point in
    a series, such as the visual properties of its marker and the text and
    font of its data label.
    """
    def __init__(self, ser, idx) -> None:
        ...
    
    @lazyproperty
    def data_label(self): # -> DataLabel:
        """
        The |DataLabel| object representing the label on this data point.
        """
        ...
    
    @lazyproperty
    def format(self): # -> ChartFormat:
        """
        The |ChartFormat| object providing access to the shape formatting
        properties of this data point, such as line and fill.
        """
        ...
    
    @lazyproperty
    def marker(self): # -> Marker:
        """
        The |Marker| instance for this point, providing access to the visual
        properties of the data point marker, such as fill and line. Setting
        these properties overrides any value set at the series level.
        """
        ...
    


class XyPoints(_BasePoints):
    """
    Sequence providing access to the individual data points in an |XySeries|
    object.
    """
    def __len__(self):
        ...
    


