"""
This type stub file was generated by pyright.
"""

from pptx.oxml.xmlchemy import BaseOxmlElement

"""lxml custom element classes for legend-related XML elements."""
class CT_Legend(BaseOxmlElement):
    """
    ``<c:legend>`` custom element class
    """
    _tag_seq = ...
    legendPos = ...
    layout = ...
    overlay = ...
    txPr = ...
    @property
    def defRPr(self):
        """
        `./c:txPr/a:p/a:pPr/a:defRPr` great-great-grandchild element, added
        with its ancestors if not present.
        """
        ...
    
    @property
    def horz_offset(self): # -> float:
        """
        The float value in ./c:layout/c:manualLayout/c:x when
        ./c:layout/c:manualLayout/c:xMode@val == "factor". 0.0 if that
        XPath expression has no match.
        """
        ...
    
    @horz_offset.setter
    def horz_offset(self, offset): # -> None:
        """
        Set the value of ./c:layout/c:manualLayout/c:x@val to *offset* and
        ./c:layout/c:manualLayout/c:xMode@val to "factor". Remove
        ./c:layout/c:manualLayout if *offset* == 0.
        """
        ...
    


class CT_LegendPos(BaseOxmlElement):
    """
    ``<c:legendPos>`` element specifying position of legend with respect to
    chart as a member of ST_LegendPos.
    """
    val = ...


