"""
This type stub file was generated by pyright.
"""

from pptx.oxml.xmlchemy import BaseOxmlElement

"""Plot-related oxml objects."""
class BaseChartElement(BaseOxmlElement):
    """
    Base class for barChart, lineChart, and other plot elements.
    """
    @property
    def cat(self): # -> Any | None:
        """
        Return the `c:cat` element of the first series in this xChart, or
        |None| if not present.
        """
        ...
    
    @property
    def cat_pt_count(self): # -> Any | Literal[0]:
        """
        Return the value of the `c:ptCount` descendent of this xChart
        element. Its parent can be one of three element types. This value
        represents the true number of (leaf) categories, although they might
        not all have a corresponding `c:pt` sibling; a category with no label
        does not get a `c:pt` element. Returns 0 if there is no `c:ptCount`
        descendent.
        """
        ...
    
    @property
    def cat_pts(self): # -> list[Any | None]:
        """
        Return a sequence representing the `c:pt` elements under the `c:cat`
        element of the first series in this xChart element. A category having
        no value will have no corresponding `c:pt` element; |None| will
        appear in that position in such cases. Items appear in `idx` order.
        Only those in the first ``<c:lvl>`` element are included in the case
        of multi-level categories.
        """
        ...
    
    @property
    def grouping_val(self): # -> Literal['standard']:
        """
        Return the value of the ``./c:grouping{val=?}`` attribute, taking
        defaults into account when items are not present.
        """
        ...
    
    def iter_sers(self): # -> Generator[Any, None, None]:
        """
        Generate each ``<c:ser>`` child element in this xChart in
        c:order/@val sequence (not document or c:idx order).
        """
        ...
    
    @property
    def sers(self): # -> tuple[Any, ...]:
        """
        Sequence of ``<c:ser>`` child elements in this xChart in c:order/@val
        sequence (not document or c:idx order).
        """
        ...
    


class CT_Area3DChart(BaseChartElement):
    """
    ``<c:area3DChart>`` element.
    """
    grouping = ...


class CT_AreaChart(BaseChartElement):
    """
    ``<c:areaChart>`` element.
    """
    _tag_seq = ...
    grouping = ...
    varyColors = ...
    ser = ...
    dLbls = ...


class CT_BarChart(BaseChartElement):
    """
    ``<c:barChart>`` element.
    """
    _tag_seq = ...
    barDir = ...
    grouping = ...
    varyColors = ...
    ser = ...
    dLbls = ...
    gapWidth = ...
    overlap = ...
    @property
    def grouping_val(self): # -> Literal['clustered']:
        """
        Return the value of the ``./c:grouping{val=?}`` attribute, taking
        defaults into account when items are not present.
        """
        ...
    


class CT_BarDir(BaseOxmlElement):
    """
    ``<c:barDir>`` child of a barChart element, specifying the orientation of
    the bars, 'bar' if they are horizontal and 'col' if they are vertical.
    """
    val = ...


class CT_BubbleChart(BaseChartElement):
    """
    ``<c:bubbleChart>`` custom element class
    """
    _tag_seq = ...
    ser = ...
    dLbls = ...
    bubble3D = ...
    bubbleScale = ...


class CT_BubbleScale(BaseChartElement):
    """
    ``<c:bubbleScale>`` custom element class
    """
    val = ...


class CT_DoughnutChart(BaseChartElement):
    """
    ``<c:doughnutChart>`` element.
    """
    _tag_seq = ...
    varyColors = ...
    ser = ...
    dLbls = ...


class CT_GapAmount(BaseOxmlElement):
    """
    ``<c:gapWidth>`` child of ``<c:barChart>`` element, also used for other
    purposes like error bars.
    """
    val = ...


class CT_Grouping(BaseOxmlElement):
    """
    ``<c:grouping>`` child of an xChart element, specifying a value like
    'clustered' or 'stacked'. Also used for variants with the same tag name
    like CT_BarGrouping.
    """
    val = ...


class CT_LineChart(BaseChartElement):
    """
    ``<c:lineChart>`` custom element class
    """
    _tag_seq = ...
    grouping = ...
    varyColors = ...
    ser = ...
    dLbls = ...


class CT_Overlap(BaseOxmlElement):
    """
    ``<c:overlap>`` element specifying bar overlap as an integer percentage
    of bar width, in range -100 to 100.
    """
    val = ...


class CT_PieChart(BaseChartElement):
    """
    ``<c:pieChart>`` custom element class
    """
    _tag_seq = ...
    varyColors = ...
    ser = ...
    dLbls = ...


class CT_RadarChart(BaseChartElement):
    """
    ``<c:radarChart>`` custom element class
    """
    _tag_seq = ...
    varyColors = ...
    ser = ...
    dLbls = ...


class CT_ScatterChart(BaseChartElement):
    """
    ``<c:scatterChart>`` custom element class
    """
    _tag_seq = ...
    varyColors = ...
    ser = ...


