"""
This type stub file was generated by pyright.
"""

def color_tohex(color, rev_byteorder): # -> Literal[0]:
    ...

def set_callback(struct, fname, callback): # -> None:
    ...

def is_buffer(buf, spec=...): # -> bool:
    ...

class _buffer_reader:
    def __init__(self, buffer) -> None:
        ...
    
    def __call__(self, _, position, p_buf, size): # -> Literal[1]:
        ...
    


class _buffer_writer:
    def __init__(self, buffer) -> None:
        ...
    
    def __call__(self, _, data, size): # -> Literal[1]:
        ...
    


def get_bufreader(buffer): # -> tuple[FPDF_FILEACCESS, tuple[Any]]:
    ...

def get_bufwriter(buffer): # -> FPDF_FILEWRITE:
    ...

def pages_c_array(pages): # -> tuple[None, Literal[0]] | tuple[Array[_Pointer[struct_fpdf_page_t__]], int]:
    ...

