"""
This type stub file was generated by pyright.
"""

import enum
from abc import ABCMeta
from typing import Generic, Optional, Type, TypeVar
from pydantic import BaseModel
from docling.datamodel.pipeline_options import BaseOptions
from docling.models.base_model import BaseModelWithOptions

A = TypeVar("A", bound=BaseModelWithOptions)
logger = ...
class FactoryMeta(BaseModel):
    kind: str
    plugin_name: str
    module: str
    ...


class BaseFactory(Generic[A], metaclass=ABCMeta):
    default_plugin_name = ...
    def __init__(self, plugin_attr_name: str, plugin_name=...) -> None:
        ...
    
    @property
    def registered_kind(self) -> list[str]:
        ...
    
    def get_enum(self) -> enum.Enum:
        ...
    
    @property
    def classes(self): # -> dict[type[BaseOptions], type[A]]:
        ...
    
    @property
    def registered_meta(self): # -> dict[type[BaseOptions], FactoryMeta]:
        ...
    
    def create_instance(self, options: BaseOptions, **kwargs) -> A:
        ...
    
    def create_options(self, kind: str, *args, **kwargs) -> BaseOptions:
        ...
    
    def register(self, cls: Type[A], plugin_name: str, plugin_module_name: str): # -> None:
        ...
    
    def load_from_plugins(self, plugin_name: Optional[str] = ..., allow_external_plugins: bool = ...): # -> None:
        ...
    
    def process_plugin(self, config, plugin_name: str, plugin_module_name: str): # -> None:
        ...
    


