"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from typing import Any, Callable, Literal, TYPE_CHECKING, TypeVar
from pydantic_core import CoreConfig, CoreSchema, SchemaValidator
from typing_extensions import ParamSpec
from . import BaseValidateHandlerProtocol, PydanticPluginProtocol, SchemaKind, SchemaTypePath

"""Pluggable schema validator for pydantic."""
if TYPE_CHECKING:
    ...
P = ParamSpec('P')
R = TypeVar('R')
Event = Literal['on_validate_python', 'on_validate_json', 'on_validate_strings']
events: list[Event] = ...
def create_schema_validator(schema: CoreSchema, schema_type: Any, schema_type_module: str, schema_type_name: str, schema_kind: SchemaKind, config: CoreConfig | None = ..., plugin_settings: dict[str, Any] | None = ...) -> SchemaValidator | PluggableSchemaValidator:
    """Create a `SchemaValidator` or `PluggableSchemaValidator` if plugins are installed.

    Returns:
        If plugins are installed then return `PluggableSchemaValidator`, otherwise return `SchemaValidator`.
    """
    ...

class PluggableSchemaValidator:
    """Pluggable schema validator."""
    __slots__ = ...
    def __init__(self, schema: CoreSchema, schema_type: Any, schema_type_path: SchemaTypePath, schema_kind: SchemaKind, config: CoreConfig | None, plugins: Iterable[PydanticPluginProtocol], plugin_settings: dict[str, Any]) -> None:
        ...
    
    def __getattr__(self, name: str) -> Any:
        ...
    


def build_wrapper(func: Callable[P, R], event_handlers: list[BaseValidateHandlerProtocol]) -> Callable[P, R]:
    ...

def filter_handlers(handler_cls: BaseValidateHandlerProtocol, method_name: str) -> bool:
    """Filter out handler methods which are not implemented by the plugin directly - e.g. are missing
    or are inherited from the protocol.
    """
    ...

