"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import List, Optional, TYPE_CHECKING, Tuple
from docling_core.types.doc.document import TableCell, TableData

"""Utils for document types."""
if TYPE_CHECKING:
    ...
def relative_path(src: Path, target: Path) -> Path:
    """Compute the relative path from `src` to `target`.

    Args:
        src (str | Path): The source directory or file path (must be absolute).
        target (str | Path): The target directory or file path (must be absolute).

    Returns:
        Path: The relative path from `src` to `target`.

    Raises:
        ValueError: If either `src` or `target` is not an absolute path.
    """
    ...

def get_html_tag_with_text_direction(html_tag: str, text: str, attrs: Optional[dict] = ...) -> str:
    """Form the HTML element with tag, text, and optional dir attribute."""
    ...

def get_text_direction(text: str) -> str:
    """Determine the text direction of a given string as LTR or RTL script."""
    ...

def otsl_extract_tokens_and_text(s: str) -> Tuple[List[str], List[str]]:
    """Extract OTSL tokens and text from an OTSL string."""
    ...

def otsl_parse_texts(texts: List[str], tokens: List[str]) -> Tuple[List[TableCell], List[List[str]]]:
    """Parse OTSL texts and tokens into table cells."""
    ...

def parse_otsl_table_content(otsl_content: str) -> TableData:
    """Parse OTSL content into TableData."""
    ...

