"""
This type stub file was generated by pyright.
"""

from warnings import warn
from ..auto import tqdm as tqdm_auto
from ..std import TqdmDeprecationWarning, tqdm
from ..utils import ObjectWrapper

"""
Thin wrappers around common functions.

Subpackages contain potentially unstable extensions.
"""
__author__ = ...
__all__ = ['tenumerate', 'tzip', 'tmap']
class DummyTqdmFile(ObjectWrapper):
    """Dummy file-like that will write to tqdm"""
    def __init__(self, wrapped) -> None:
        ...
    
    def write(self, x, nolock=...): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    


def builtin_iterable(func):
    """Returns `func`"""
    ...

def tenumerate(iterable, start=..., total=..., tqdm_class=..., **tqdm_kwargs): # -> tqdm | enumerate[Any]:
    """
    Equivalent of `numpy.ndenumerate` or builtin `enumerate`.

    Parameters
    ----------
    tqdm_class  : [default: tqdm.auto.tqdm].
    """
    ...

def tzip(iter1, *iter2plus, **tqdm_kwargs): # -> Generator[tuple[Any, ...], Any, None]:
    """
    Equivalent of builtin `zip`.

    Parameters
    ----------
    tqdm_class  : [default: tqdm.auto.tqdm].
    """
    ...

def tmap(function, *sequences, **tqdm_kwargs): # -> Generator[Any, Any, None]:
    """
    Equivalent of builtin `map`.

    Parameters
    ----------
    tqdm_class  : [default: tqdm.auto.tqdm].
    """
    ...

