"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, TYPE_CHECKING, TypeVar
from .element import Element

"""
Base renderer class
"""
if TYPE_CHECKING:
    ...
_T = TypeVar("_T", bound="Renderer")
_charref_bak = ...
class Renderer:
    """The base class of renderers.

    A custom renderer should subclass this class and include your own render functions.

    A render function should:

    * be named as ``render_<element_name>``, where the ``element_name`` is the snake
      case form of the element class name, the renderer will search the corresponding
      function in this way.
    * accept the element instance and return any output you want.

    If no corresponding render function is found, renderer will fallback to call
    :meth:`Renderer.render_children`.
    """
    delegate: bool = ...
    _charref = ...
    def __init__(self) -> None:
        ...
    
    def __enter__(self: _T) -> _T:
        """Provide a context so that root_node can be reset after render."""
        ...
    
    def __exit__(self, *args: Any) -> None:
        ...
    
    def render(self, element: Element) -> Any:
        """Renders the given element to string.

        :param element: a element to be rendered.
        :returns: the output string or any values.
        """
        ...
    
    def render_children(self, element: Any) -> Any:
        """
        Recursively renders child elements. Joins the rendered
        strings with no space in between.

        If newlines / spaces are needed between elements, add them
        in their respective templates, or override this function
        in the renderer subclass, so that whitespace won't seem to
        appear magically for anyone reading your program.

        :param element: a branch node who has children attribute.
        """
        ...
    


_F = TypeVar("_F", bound=Callable)
def force_delegate(func: _F) -> _F:
    """
    A decorator to allow delegation for the specified method even if cls.delegate = False
    """
    ...

