"""
This type stub file was generated by pyright.
"""

import numpy as np
from enum import Enum
from typing import List, Tuple
from ..ch_ppocr_rec.typings import TextRecOutput, WordInfo

class Direction(Enum):
    HORIZONTAL = ...
    VERTICAL = ...


class CalRecBoxes:
    """计算识别文字的汉字单字和英文单词的坐标框。
    代码借鉴自PaddlePaddle/PaddleOCR和fanqie03/char-detection"""
    def __call__(self, imgs: List[np.ndarray], dt_boxes: np.ndarray, rec_res: TextRecOutput, return_single_char_box: bool = ...) -> TextRecOutput:
        ...
    
    @staticmethod
    def get_box_direction(box: np.ndarray) -> Direction:
        ...
    
    def cal_ocr_word_box(self, rec_txt: str, bbox: np.ndarray, word_info: WordInfo, return_single_char_box: bool = ...) -> Tuple[List[str], List[List[List[float]]], List[float]]:
        """Calculate the detection frame for each word based on the results of recognition and detection of ocr
        汉字坐标是单字的
        英语坐标是单词级别的
        三种情况：
        1. 全是汉字
        2. 全是英文
        3. 中英混合
        """
        ...
    
    def calc_en_num_box(self, line_cols: List[List[int]], avg_char_width: float, avg_col_width: float, bbox_points: Tuple[float, float, float, float]) -> List[List[List[float]]]:
        ...
    
    @staticmethod
    def calc_box(line_cols: List[int], avg_char_width: float, avg_col_width: float, bbox_points: Tuple[float, float, float, float]) -> List[List[List[float]]]:
        ...
    
    @staticmethod
    def calc_avg_char_width(word_col: List[int], each_col_width: float) -> float:
        ...
    
    @staticmethod
    def calc_all_char_avg_width(width_list: List[float], bbox_x0: float, bbox_x1: float, txt_len: int) -> float:
        ...
    
    @staticmethod
    def adjust_box_overlap(word_box_list: List[List[List[float]]]) -> List[List[List[float]]]:
        ...
    
    def reverse_rotate_crop_image(self, bbox_points: np.ndarray, word_points_list: List[List[List[float]]], direction: Direction) -> List[List[List[int]]]:
        """
        get_rotate_crop_image的逆操作
        img为原图
        part_img为crop后的图
        bbox_points为part_img中对应在原图的bbox, 四个点，左上，右上，右下，左下
        part_points为在part_img中的点[(x, y), (x, y)]
        """
        ...
    
    @staticmethod
    def s_rotate(angle, valuex, valuey, pointx, pointy): # -> list[Any]:
        """绕pointx,pointy顺时针旋转
        https://blog.csdn.net/qq_38826019/article/details/84233397
        """
        ...
    
    @staticmethod
    def order_points(ori_box: List[List[int]]) -> List[List[int]]:
        """矩形框顺序排列"""
        ...
    


