"""
This type stub file was generated by pyright.
"""

import json
import pickle
from enum import Enum
from pathlib import Path
from typing import Any, Callable, TYPE_CHECKING
from typing_extensions import deprecated

if not TYPE_CHECKING:
    ...
class Protocol(str, Enum):
    json = ...
    pickle = ...


@deprecated('`load_str_bytes` is deprecated.', category=None)
def load_str_bytes(b: str | bytes, *, content_type: str | None = ..., encoding: str = ..., proto: Protocol | None = ..., allow_pickle: bool = ..., json_loads: Callable[[str], Any] = ...) -> Any:
    ...

@deprecated('`load_file` is deprecated.', category=None)
def load_file(path: str | Path, *, content_type: str | None = ..., encoding: str = ..., proto: Protocol | None = ..., allow_pickle: bool = ..., json_loads: Callable[[str], Any] = ...) -> Any:
    ...

