"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, TypedDict
from pptx.enum.shapes import MSO_SHAPE
from typing_extensions import TypeAlias

"""Mappings from the ISO/IEC 29500 spec.

Some of these are inferred from PowerPoint application behavior
"""
GRAPHIC_DATA_URI_CHART = ...
GRAPHIC_DATA_URI_OLEOBJ = ...
GRAPHIC_DATA_URI_TABLE = ...
if TYPE_CHECKING:
    ...
AdjustmentValue: TypeAlias = "tuple[str, int]"
class ShapeSpec(TypedDict):
    basename: str
    avLst: tuple[AdjustmentValue, ...]
    ...


autoshape_types: dict[MSO_SHAPE, ShapeSpec] = ...
