"""
This type stub file was generated by pyright.
"""

import numpy as np
from scipy.optimize import Bounds, LinearConstraint, NonlinearConstraint
from .common._nonlinear_constraints import process_nl_constraints
from .common._linear_constraints import combine_multiple_linear_constraints, separate_LC_into_eq_and_ineq
from .common._bounds import process_bounds
from enum import Enum
from .common._project import _project
from .common.linalg import get_arrays_tol
from .cobyla.cobyla import cobyla
from collections.abc import Iterable

class ConstraintType(Enum):
    LINEAR_OBJECT = ...
    NONLINEAR_OBJECT = ...
    LINEAR_DICT = ...
    NONLINEAR_DICT = ...


def get_constraint_type(constraint): # -> Literal[ConstraintType.LINEAR_DICT, ConstraintType.NONLINEAR_DICT, ConstraintType.LINEAR_OBJECT, ConstraintType.NONLINEAR_OBJECT]:
    ...

def process_constraints(constraints): # -> tuple[None, None] | tuple[LinearConstraint | Any | None, Callable[..., _Array1D[float64] | NDArray[float64]] | None]:
    ...

def minimize(fun, x0, args=..., method=..., bounds=..., constraints=..., callback=..., options=...):
    ...

