"""
This type stub file was generated by pyright.
"""

from typing import Callable, Iterator, List
from lxml import etree
from typing_extensions import TypeAlias
from docx.enum.section import WD_HEADER_FOOTER, WD_ORIENTATION, WD_SECTION_START
from docx.oxml.shared import CT_OnOff
from docx.oxml.table import CT_Tbl
from docx.oxml.text.paragraph import CT_P
from docx.oxml.xmlchemy import BaseOxmlElement
from docx.shared import Length

"""Section-related custom element classes."""
BlockElement: TypeAlias = "CT_P | CT_Tbl"
class CT_HdrFtr(BaseOxmlElement):
    """`w:hdr` and `w:ftr`, the root element for header and footer part respectively."""
    add_p: Callable[[], CT_P]
    p_lst: List[CT_P]
    tbl_lst: List[CT_Tbl]
    _insert_tbl: Callable[[CT_Tbl], CT_Tbl]
    p = ...
    tbl = ...
    @property
    def inner_content_elements(self) -> List[CT_P | CT_Tbl]:
        """Generate all `w:p` and `w:tbl` elements in this header or footer.

        Elements appear in document order. Elements shaded by nesting in a `w:ins` or
        other "wrapper" element will not be included.
        """
        ...
    


class CT_HdrFtrRef(BaseOxmlElement):
    """`w:headerReference` and `w:footerReference` elements."""
    type_: WD_HEADER_FOOTER = ...
    rId: str = ...


class CT_PageMar(BaseOxmlElement):
    """``<w:pgMar>`` element, defining page margins."""
    top: Length | None = ...
    right: Length | None = ...
    bottom: Length | None = ...
    left: Length | None = ...
    header: Length | None = ...
    footer: Length | None = ...
    gutter: Length | None = ...


class CT_PageSz(BaseOxmlElement):
    """``<w:pgSz>`` element, defining page dimensions and orientation."""
    w: Length | None = ...
    h: Length | None = ...
    orient: WD_ORIENTATION = ...


class CT_SectPr(BaseOxmlElement):
    """`w:sectPr` element, the container element for section properties."""
    get_or_add_pgMar: Callable[[], CT_PageMar]
    get_or_add_pgSz: Callable[[], CT_PageSz]
    get_or_add_titlePg: Callable[[], CT_OnOff]
    get_or_add_type: Callable[[], CT_SectType]
    _add_footerReference: Callable[[], CT_HdrFtrRef]
    _add_headerReference: Callable[[], CT_HdrFtrRef]
    _remove_titlePg: Callable[[], None]
    _remove_type: Callable[[], None]
    _tag_seq = ...
    headerReference = ...
    footerReference = ...
    type: CT_SectType | None = ...
    pgSz: CT_PageSz | None = ...
    pgMar: CT_PageMar | None = ...
    titlePg: CT_OnOff | None = ...
    def add_footerReference(self, type_: WD_HEADER_FOOTER, rId: str) -> CT_HdrFtrRef:
        """Return newly added CT_HdrFtrRef element of `type_` with `rId`.

        The element tag is `w:footerReference`.
        """
        ...
    
    def add_headerReference(self, type_: WD_HEADER_FOOTER, rId: str) -> CT_HdrFtrRef:
        """Return newly added CT_HdrFtrRef element of `type_` with `rId`.

        The element tag is `w:headerReference`.
        """
        ...
    
    @property
    def bottom_margin(self) -> Length | None:
        """Value of the `w:bottom` attr of `<w:pgMar>` child element, as |Length|.

        |None| when either the element or the attribute is not present.
        """
        ...
    
    @bottom_margin.setter
    def bottom_margin(self, value: int | Length | None): # -> None:
        ...
    
    def clone(self) -> CT_SectPr:
        """Return an exact duplicate of this ``<w:sectPr>`` element tree suitable for
        use in adding a section break.

        All rsid* attributes are removed from the root ``<w:sectPr>`` element.
        """
        ...
    
    @property
    def footer(self) -> Length | None:
        """Distance from bottom edge of page to bottom edge of the footer.

        This is the value of the `w:footer` attribute in the `w:pgMar` child element,
        as a |Length| object, or |None| if either the element or the attribute is not
        present.
        """
        ...
    
    @footer.setter
    def footer(self, value: int | Length | None): # -> None:
        ...
    
    def get_footerReference(self, type_: WD_HEADER_FOOTER) -> CT_HdrFtrRef | None:
        """Return footerReference element of `type_` or None if not present."""
        ...
    
    def get_headerReference(self, type_: WD_HEADER_FOOTER) -> CT_HdrFtrRef | None:
        """Return headerReference element of `type_` or None if not present."""
        ...
    
    @property
    def gutter(self) -> Length | None:
        """The value of the ``w:gutter`` attribute in the ``<w:pgMar>`` child element,
        as a |Length| object, or |None| if either the element or the attribute is not
        present."""
        ...
    
    @gutter.setter
    def gutter(self, value: int | Length | None): # -> None:
        ...
    
    @property
    def header(self) -> Length | None:
        """Distance from top edge of page to top edge of header.

        This value comes from the `w:header` attribute on the `w:pgMar` child element.
        |None| if either the element or the attribute is not present.
        """
        ...
    
    @header.setter
    def header(self, value: int | Length | None): # -> None:
        ...
    
    def iter_inner_content(self) -> Iterator[CT_P | CT_Tbl]:
        """Generate all `w:p` and `w:tbl` elements in this section.

        Elements appear in document order. Elements shaded by nesting in a `w:ins` or
        other "wrapper" element will not be included.
        """
        ...
    
    @property
    def left_margin(self) -> Length | None:
        """The value of the ``w:left`` attribute in the ``<w:pgMar>`` child element, as
        a |Length| object, or |None| if either the element or the attribute is not
        present."""
        ...
    
    @left_margin.setter
    def left_margin(self, value: int | Length | None): # -> None:
        ...
    
    @property
    def orientation(self) -> WD_ORIENTATION:
        """`WD_ORIENTATION` member indicating page-orientation for this section.

        This is the value of the `orient` attribute on the `w:pgSz` child, or
        `WD_ORIENTATION.PORTRAIT` if not present.
        """
        ...
    
    @orientation.setter
    def orientation(self, value: WD_ORIENTATION | None): # -> None:
        ...
    
    @property
    def page_height(self) -> Length | None:
        """Value in EMU of the `h` attribute of the `w:pgSz` child element.

        |None| if not present.
        """
        ...
    
    @page_height.setter
    def page_height(self, value: Length | None): # -> None:
        ...
    
    @property
    def page_width(self) -> Length | None:
        """Value in EMU of the ``w`` attribute of the ``<w:pgSz>`` child element.

        |None| if not present.
        """
        ...
    
    @page_width.setter
    def page_width(self, value: Length | None): # -> None:
        ...
    
    @property
    def preceding_sectPr(self) -> CT_SectPr | None:
        """SectPr immediately preceding this one or None if this is the first."""
        ...
    
    def remove_footerReference(self, type_: WD_HEADER_FOOTER) -> str:
        """Return rId of w:footerReference child of `type_` after removing it."""
        ...
    
    def remove_headerReference(self, type_: WD_HEADER_FOOTER): # -> str:
        """Return rId of w:headerReference child of `type_` after removing it."""
        ...
    
    @property
    def right_margin(self) -> Length | None:
        """The value of the ``w:right`` attribute in the ``<w:pgMar>`` child element, as
        a |Length| object, or |None| if either the element or the attribute is not
        present."""
        ...
    
    @right_margin.setter
    def right_margin(self, value: Length | None): # -> None:
        ...
    
    @property
    def start_type(self) -> WD_SECTION_START:
        """The member of the ``WD_SECTION_START`` enumeration corresponding to the value
        of the ``val`` attribute of the ``<w:type>`` child element, or
        ``WD_SECTION_START.NEW_PAGE`` if not present."""
        ...
    
    @start_type.setter
    def start_type(self, value: WD_SECTION_START | None): # -> None:
        ...
    
    @property
    def titlePg_val(self) -> bool:
        """Value of `w:titlePg/@val` or |False| if `./w:titlePg` is not present."""
        ...
    
    @titlePg_val.setter
    def titlePg_val(self, value: bool | None): # -> None:
        ...
    
    @property
    def top_margin(self) -> Length | None:
        """The value of the ``w:top`` attribute in the ``<w:pgMar>`` child element, as a
        |Length| object, or |None| if either the element or the attribute is not
        present."""
        ...
    
    @top_margin.setter
    def top_margin(self, value: Length | None): # -> None:
        ...
    


class CT_SectType(BaseOxmlElement):
    """``<w:sectType>`` element, defining the section start type."""
    val: WD_SECTION_START | None = ...


class _SectBlockElementIterator:
    """Generates the block-item XML elements in a section.

    A block-item element is a `CT_P` (paragraph) or a `CT_Tbl` (table).
    """
    _compiled_blocks_xpath: etree.XPath | None = ...
    _compiled_count_xpath: etree.XPath | None = ...
    def __init__(self, sectPr: CT_SectPr) -> None:
        ...
    
    @classmethod
    def iter_sect_block_elements(cls, sectPr: CT_SectPr) -> Iterator[BlockElement]:
        """Generate each CT_P or CT_Tbl element within extents governed by `sectPr`."""
        ...
    


