"""
This type stub file was generated by pyright.
"""

import datetime as dt
from typing import Any, TYPE_CHECKING, Tuple
from docx.shared import Emu, Length, RGBColor

"""Simple-type classes, corresponding to ST_* schema items.

These provide validation and format translation for values stored in XML element
attributes. Naming generally corresponds to the simple type in the associated XML
schema.
"""
if TYPE_CHECKING:
    ...
class BaseSimpleType:
    """Base class for simple-types."""
    @classmethod
    def from_xml(cls, xml_value: str) -> Any:
        ...
    
    @classmethod
    def to_xml(cls, value: Any) -> str:
        ...
    
    @classmethod
    def convert_from_xml(cls, str_value: str) -> Any:
        ...
    
    @classmethod
    def convert_to_xml(cls, value: Any) -> str:
        ...
    
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    
    @classmethod
    def validate_int(cls, value: object): # -> None:
        ...
    
    @classmethod
    def validate_int_in_range(cls, value: int, min_inclusive: int, max_inclusive: int) -> None:
        ...
    
    @classmethod
    def validate_string(cls, value: Any) -> str:
        ...
    


class BaseIntType(BaseSimpleType):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> int:
        ...
    
    @classmethod
    def convert_to_xml(cls, value: int) -> str:
        ...
    
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class BaseStringType(BaseSimpleType):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> str:
        ...
    
    @classmethod
    def convert_to_xml(cls, value: str) -> str:
        ...
    
    @classmethod
    def validate(cls, value: str): # -> None:
        ...
    


class BaseStringEnumerationType(BaseStringType):
    _members: Tuple[str, ...]
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class XsdAnyUri(BaseStringType):
    """There's a regex in the spec this is supposed to meet...

    but current assessment is that spending cycles on validating wouldn't be worth it
    for the number of programming errors it would catch.
    """
    ...


class XsdBoolean(BaseSimpleType):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> bool:
        ...
    
    @classmethod
    def convert_to_xml(cls, value: bool) -> str:
        ...
    
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class XsdId(BaseStringType):
    """String that must begin with a letter or underscore and cannot contain any colons.

    Not fully validated because not used in external API.
    """
    ...


class XsdInt(BaseIntType):
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class XsdLong(BaseIntType):
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class XsdString(BaseStringType):
    ...


class XsdStringEnumeration(BaseStringEnumerationType):
    """Set of enumerated xsd:string values."""
    ...


class XsdToken(BaseStringType):
    """Xsd:string with whitespace collapsing, e.g. multiple spaces reduced to one,
    leading and trailing space stripped."""
    ...


class XsdUnsignedInt(BaseIntType):
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class XsdUnsignedLong(BaseIntType):
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class ST_BrClear(XsdString):
    @classmethod
    def validate(cls, value: str) -> None:
        ...
    


class ST_BrType(XsdString):
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class ST_Coordinate(BaseIntType):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> Length:
        ...
    
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class ST_CoordinateUnqualified(XsdLong):
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class ST_DateTime(BaseSimpleType):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> dt.datetime:
        """Convert an xsd:dateTime string to a datetime object."""
        ...
    
    @classmethod
    def convert_to_xml(cls, value: dt.datetime) -> str:
        ...
    
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class ST_DecimalNumber(XsdInt):
    ...


class ST_DrawingElementId(XsdUnsignedInt):
    ...


class ST_HexColor(BaseStringType):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> RGBColor | str:
        ...
    
    @classmethod
    def convert_to_xml(cls, value: RGBColor) -> str:
        """Keep alpha hex numerals all uppercase just for consistency."""
        ...
    
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class ST_HexColorAuto(XsdStringEnumeration):
    """Value for `w:color/[@val="auto"] attribute setting."""
    AUTO = ...
    _members = ...


class ST_HpsMeasure(XsdUnsignedLong):
    """Half-point measure, e.g. 24.0 represents 12.0 points."""
    @classmethod
    def convert_from_xml(cls, str_value: str) -> Length:
        ...
    
    @classmethod
    def convert_to_xml(cls, value: int | Length) -> str:
        ...
    


class ST_Merge(XsdStringEnumeration):
    """Valid values for <w:xMerge val=""> attribute."""
    CONTINUE = ...
    RESTART = ...
    _members = ...


class ST_OnOff(XsdBoolean):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> bool:
        ...
    


class ST_PositiveCoordinate(XsdLong):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> Length:
        ...
    
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class ST_RelationshipId(XsdString):
    ...


class ST_SignedTwipsMeasure(XsdInt):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> Length:
        ...
    
    @classmethod
    def convert_to_xml(cls, value: int | Length) -> str:
        ...
    


class ST_String(XsdString):
    ...


class ST_TblLayoutType(XsdString):
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class ST_TblWidth(XsdString):
    @classmethod
    def validate(cls, value: Any) -> None:
        ...
    


class ST_TwipsMeasure(XsdUnsignedLong):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> Length:
        ...
    
    @classmethod
    def convert_to_xml(cls, value: int | Length) -> str:
        ...
    


class ST_UniversalMeasure(BaseSimpleType):
    @classmethod
    def convert_from_xml(cls, str_value: str) -> Emu:
        ...
    


class ST_VerticalAlignRun(XsdStringEnumeration):
    """Valid values for `w:vertAlign/@val`."""
    BASELINE = ...
    SUPERSCRIPT = ...
    SUBSCRIPT = ...
    _members = ...


