"""
This type stub file was generated by pyright.
"""

import abc
import numpy as np
from dataclasses import dataclass
from enum import Enum
from typing import Dict
from ..utils.typings import EngineType, ModelType, OCRVersion, TaskType

cur_dir = ...
MODEL_URL_PATH = ...
def get_engine(engine_type: EngineType): # -> type[OrtInferSession] | type[OpenVINOInferSession] | type[PaddleInferSession] | type[TorchInferSession]:
    ...

@dataclass
class FileInfo:
    engine_type: EngineType
    ocr_version: OCRVersion
    task_type: TaskType
    lang_type: Enum
    model_type: ModelType
    ...


class InferSession(abc.ABC):
    model_info = ...
    DEFAULT_MODEL_PATH = ...
    @abc.abstractmethod
    def __init__(self, config) -> None:
        ...
    
    @abc.abstractmethod
    def __call__(self, input_content: np.ndarray) -> np.ndarray:
        ...
    
    @abc.abstractmethod
    def have_key(self, key: str = ...) -> bool:
        ...
    
    @classmethod
    def get_model_url(cls, file_info: FileInfo) -> Dict[str, str]:
        ...
    
    @classmethod
    def get_dict_key_url(cls, file_info: FileInfo) -> str:
        ...
    


